package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

const iosEntrySource = `// Code generated by mygo build. DO NOT EDIT.
//go:build ios && cgo

package main

import "C"

//export MyGoIOSMain
func MyGoIOSMain() { main() }
`

// buildIOS keeps UIKit's main() outside the Go archive: UIApplicationMain
// owns the OS main thread, and its delegate enters the user's Go main.
func buildIOS(c *Config, arch string, opts buildOptions) ([]string, error) {
	if runtime.GOOS != "darwin" {
		return nil, fmt.Errorf("iOS builds require macOS and Xcode")
	}
	if arch != "arm64" {
		return nil, fmt.Errorf("iOS currently supports arm64 (device and Apple Silicon simulator)")
	}
	if opts.iosDevice != "" && (opts.iosTeam == "" || opts.iosSimulator) {
		return nil, fmt.Errorf("-ios-device requires a development team and a device build")
	}
	if c.FrontendDist != "" || c.Updates != nil {
		return nil, fmt.Errorf("iOS currently supports native WindowOptions.Content without a web frontend or desktop updater")
	}
	if err := validateIOSPackaging(c, opts); err != nil {
		return nil, err
	}
	if opts.iosExportMethod != "" {
		opts.iosArchive = true
	}
	privacy, err := iosPrivacyManifest(c)
	if err != nil {
		return nil, err
	}
	minimum := c.IOS.MinimumSystemVersion
	if minimum == "" {
		minimum = "15.0"
	}
	if !regexp.MustCompile(`^\d+\.\d+(\.\d+)?$`).MatchString(minimum) {
		return nil, fmt.Errorf("ios.minimumSystemVersion must be a numeric version")
	}
	major, _, _ := strings.Cut(minimum, ".")
	if n, err := strconv.Atoi(major); err != nil || n < 15 {
		return nil, fmt.Errorf("the iOS backend requires iOS 15.0 or later")
	}
	sdk, target := "iphoneos", "ios-arm64"
	triple := "arm64-apple-ios" + minimum
	if opts.iosSimulator {
		sdk, target = "iphonesimulator", "ios-simulator-arm64"
		triple += "-simulator"
	}
	sdkPath, err := exec.Command("xcrun", "--sdk", sdk, "--show-sdk-path").Output()
	if err != nil {
		return nil, fmt.Errorf("finding %s SDK: %w", sdk, err)
	}
	out := c.path(c.Out)
	if err := os.MkdirAll(out, 0o755); err != nil {
		return nil, err
	}
	stage, err := os.MkdirTemp(out, ".staging-"+target+"-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(stage)
	host := filepath.Join(stage, "MyGoHost")
	project := filepath.Join(host, "MyGoApp.xcodeproj")
	if err := os.MkdirAll(project, 0o755); err != nil {
		return nil, err
	}
	entry := filepath.Join(opts.work, "mygo_ios_entry.go")
	virtual := filepath.Join(opts.pkg, "mygo_ios_entry.go")
	if _, err := os.Lstat(virtual); !os.IsNotExist(err) {
		return nil, fmt.Errorf("%s is in the way of the generated iOS entry", virtual)
	}
	if err := os.WriteFile(entry, []byte(iosEntrySource), 0o644); err != nil {
		return nil, err
	}
	entries := make(map[string]string, len(opts.overlay)+1)
	for k, v := range opts.overlay {
		entries[k] = v
	}
	entries[virtual] = entry
	overlay, err := writeOverlay(filepath.Join(opts.work, "ios-overlay.json"), entries)
	if err != nil {
		return nil, err
	}
	ldflags := "-compressdwarf=false" + packageFlags(c)
	if !opts.debug {
		ldflags += " -X github.com/egoist/mygo.production=1"
	}
	flags := []string{"-buildmode=c-archive", "-trimpath", "-overlay", overlay, "-ldflags", ldflags}
	flags = append(flags, productionTags(opts.debug)...)
	if opts.debug {
		flags = append(flags, "-gcflags=all=-N -l")
	}
	compilerFlags := "-g -isysroot " + strconv.Quote(strings.TrimSpace(string(sdkPath))) + " -target " + triple
	logf("building iOS native UI (%s, cgo enabled)", sdk)
	if err := buildBinary(c, filepath.Join(host, "libmygo.a"), []string{
		"GOOS=ios", "GOARCH=arm64", "CGO_ENABLED=1", "CC=xcrun --sdk " + sdk + " clang",
		"CGO_CFLAGS=" + compilerFlags, "CGO_LDFLAGS=" + compilerFlags,
	}, flags...); err != nil {
		return nil, err
	}
	res, err := c.appResources("ios", arch)
	if err != nil {
		return nil, err
	}
	// A root-level Resources directory makes codesign interpret a flat
	// iOS bundle as a macOS bundle and treat its profile as nested code.
	if err := os.MkdirAll(filepath.Join(host, "MyGoResources"), 0o755); err != nil {
		return nil, err
	}
	if err := copyResources(res, filepath.Join(host, "MyGoResources")); err != nil {
		return nil, err
	}
	if err := iosLaunchAssets(c, host); err != nil {
		return nil, err
	}
	if err := iosIconAssets(c, host); err != nil {
		return nil, err
	}
	for name, data := range map[string][]byte{
		"main.m":                            []byte("extern int mygo_ios_start(void);\nint main(int argc, char **argv) { return mygo_ios_start(); }\n"),
		"Info.plist":                        iosInfoPlist(c, minimum),
		"MyGoApp.xcodeproj/project.pbxproj": []byte(iosProject(c, minimum, opts.iosTeam)),
	} {
		if err := os.WriteFile(filepath.Join(host, name), data, 0o644); err != nil {
			return nil, err
		}
	}
	if err := os.WriteFile(filepath.Join(host, "PrivacyInfo.xcprivacy"), privacy, 0o644); err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(host, "MyGo.entitlements"), iosEntitlements(c), 0o644); err != nil {
		return nil, err
	}
	derived := filepath.Join(opts.work, "ios-derived")
	configuration := "Release"
	if opts.debug && !opts.iosArchive {
		configuration = "Debug"
	}
	args := []string{"-quiet", "-project", project, "-scheme", "MyGoApp", "-configuration", configuration, "-sdk", sdk,
		"-derivedDataPath", derived, "ARCHS=arm64", "ONLY_ACTIVE_ARCH=YES"}
	archive := filepath.Join(stage, c.executableName()+".xcarchive")
	if opts.iosArchive {
		args = append(args, "-destination", "generic/platform=iOS", "-archivePath", archive)
	} else if opts.iosDevice != "" {
		args = append(args, "-destination", "id="+opts.iosDevice)
	}
	if opts.iosTeam == "" || opts.iosSimulator {
		args = append(args, "CODE_SIGNING_ALLOWED=NO")
	} else if c.IOS.Signing.Style != "manual" {
		args = append(args, "-allowProvisioningUpdates", "-allowProvisioningDeviceRegistration")
	}
	action := "build"
	if opts.iosArchive {
		action = "archive"
	}
	args = append(args, action)
	logf("packaging UIKit host with Xcode")
	if err := command("xcodebuild", args...); err != nil {
		return nil, err
	}
	app := filepath.Join(stage, c.executableName()+".app")
	source := filepath.Join(derived, "Build", "Products", configuration+"-"+sdk, "MyGoApp.app")
	if opts.iosArchive {
		source = filepath.Join(archive, "Products", "Applications", "MyGoApp.app")
	}
	if err := copyResource(source, app); err != nil {
		return nil, err
	}
	symbolBundle := filepath.Join(derived, "Build", "Products", configuration+"-"+sdk, "MyGoApp.app.dSYM")
	if opts.iosArchive {
		symbolBundle = filepath.Join(archive, "dSYMs", "MyGoApp.app.dSYM")
	} else {
		copyTo := filepath.Join(stage, c.executableName()+".app.dSYM")
		if err := copyResource(symbolBundle, copyTo); err != nil {
			return nil, fmt.Errorf("preserving iOS symbols: %w", err)
		}
		symbolBundle = copyTo
	}
	if err := iosWriteCheckReport(app, symbolBundle, stage, "BuildReport.json", opts.iosTeam == "" || opts.iosSimulator, false); err != nil {
		return nil, err
	}
	if opts.iosExportMethod != "" {
		exportOptions := filepath.Join(host, "ExportOptions.plist")
		if err := os.WriteFile(exportOptions, iosExportOptions(c, opts.iosExportMethod, opts.iosTeam), 0o644); err != nil {
			return nil, err
		}
		exportArgs := []string{"-quiet", "-exportArchive", "-archivePath", archive, "-exportPath", filepath.Join(stage, "Export"), "-exportOptionsPlist", exportOptions}
		if c.IOS.Signing.Style != "manual" {
			exportArgs = append(exportArgs, "-allowProvisioningUpdates")
		}
		if err := command("xcodebuild", exportArgs...); err != nil {
			return nil, fmt.Errorf("exporting iOS archive: %w", err)
		}
		ipas, err := filepath.Glob(filepath.Join(stage, "Export", "*.ipa"))
		if err != nil || len(ipas) != 1 {
			return nil, fmt.Errorf("export must produce exactly one IPA")
		}
		verify := filepath.Join(stage, ".export-check")
		payload, err := extractIOSIPA(ipas[0], verify)
		if err != nil {
			return nil, err
		}
		err = iosWriteCheckReport(payload, symbolBundle, stage, "ExportReport.json", false, opts.iosExportMethod == "app-store-connect")
		os.RemoveAll(verify)
		if err != nil {
			return nil, fmt.Errorf("checking exported IPA: %w", err)
		}
	}
	final := filepath.Join(out, target)
	if err := replacePath(stage, final); err != nil {
		return nil, err
	}
	if opts.iosTeam == "" && !opts.iosSimulator {
		logf("unsigned device build; set ios.developmentTeam or -ios-team to install")
	}
	artifacts := []string{filepath.Join(final, filepath.Base(app)), filepath.Join(final, "MyGoHost", "MyGoApp.xcodeproj")}
	artifacts = append(artifacts, filepath.Join(final, "BuildReport.json"))
	if !opts.iosArchive {
		artifacts = append(artifacts, filepath.Join(final, c.executableName()+".app.dSYM"))
	}
	if opts.iosArchive {
		artifacts = append(artifacts, filepath.Join(final, filepath.Base(archive)))
	}
	if opts.iosExportMethod != "" {
		artifacts = append(artifacts, filepath.Join(final, "ExportReport.json"))
		ipas, err := filepath.Glob(filepath.Join(final, "Export", "*.ipa"))
		if err != nil {
			return nil, err
		}
		artifacts = append(artifacts, ipas...)
	}
	return artifacts, nil
}

func iosInfoPlist(c *Config, minimum string) []byte {
	d := map[string]any{
		"CFBundleIdentifier": c.Identifier, "CFBundleName": c.Name, "CFBundleDisplayName": c.Name,
		"CFBundleExecutable": "$(EXECUTABLE_NAME)", "CFBundlePackageType": "APPL",
		"CFBundleShortVersionString": c.Version, "CFBundleVersion": iosBuildNumber(c),
		"MinimumOSVersion": minimum, "LSRequiresIPhoneOS": true,
		"UILaunchStoryboardName": "LaunchScreen",
		"MyGoLaunchScreen": map[string]any{
			"Title": iosLaunchTitle(c), "Image": c.IOS.LaunchScreen.Image != "",
			"BackgroundColor": c.IOS.LaunchScreen.BackgroundColor,
			"ForegroundColor": c.IOS.LaunchScreen.ForegroundColor,
			"FadeDurationMs":  c.IOS.LaunchScreen.FadeDurationMs,
		},
		"UIApplicationSceneManifest": map[string]any{
			"UIApplicationSupportsMultipleScenes": false,
			"UISceneConfigurations": map[string]any{
				"UIWindowSceneSessionRoleApplication": []any{map[string]any{
					"UISceneConfigurationName": "MyGo", "UISceneDelegateClassName": "MyGoScene",
				}},
			},
		},
		"UIRequiredDeviceCapabilities":          []any{"arm64"},
		"UISupportedInterfaceOrientations":      []any{"UIInterfaceOrientationPortrait", "UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight"},
		"UISupportedInterfaceOrientations~ipad": []any{"UIInterfaceOrientationPortrait", "UIInterfaceOrientationPortraitUpsideDown", "UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight"},
	}
	iosDocumentTypes(c, d)
	if len(c.URLSchemes) > 0 {
		schemes := make([]any, len(c.URLSchemes))
		for i, s := range c.URLSchemes {
			schemes[i] = s
		}
		d["CFBundleURLTypes"] = []any{map[string]any{"CFBundleURLName": c.Identifier, "CFBundleURLSchemes": schemes}}
	}
	for k, v := range c.IOS.InfoPlist {
		d[k] = v
	}
	var b bytes.Buffer
	b.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<plist version=\"1.0\">\n")
	writePlistValue(&b, d, "")
	b.WriteString("</plist>\n")
	return b.Bytes()
}

// A small, exported Xcode project lets developers inspect the native host
// and sign it in Xcode without changing their Go application sources.
func iosProject(c *Config, minimum, team string) string {
	iconGroup, iconBuild, iconObjects := "", "", ""
	iconSetting := ""
	if c.Icon != "" {
		iconSetting = " ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;"
		iconGroup = ", A00000000000000000000020"
		iconBuild = ", A00000000000000000000021"
		iconObjects = ` A00000000000000000000020 = {isa = PBXFileReference; path = Assets.xcassets; sourceTree = "<group>"; lastKnownFileType = folder.assetcatalog; };
 A00000000000000000000021 = {isa = PBXBuildFile; fileRef = A00000000000000000000020; };
`
	}
	settings := fmt.Sprintf(`PRODUCT_NAME = MyGoApp; PRODUCT_BUNDLE_IDENTIFIER = %s; INFOPLIST_FILE = Info.plist; IPHONEOS_DEPLOYMENT_TARGET = %s; TARGETED_DEVICE_FAMILY = "1,2"; CLANG_ENABLE_OBJC_ARC = YES; ALWAYS_SEARCH_USER_PATHS = NO; ENABLE_BITCODE = NO; CODE_SIGN_ENTITLEMENTS = MyGo.entitlements; SKIP_INSTALL = NO; DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym"; GCC_GENERATE_DEBUGGING_SYMBOLS = YES; STRIP_INSTALLED_PRODUCT = NO; CODE_SIGN_STYLE = Automatic; DEVELOPMENT_TEAM = %s; CODE_SIGN_IDENTITY = "Apple Development"; OTHER_LDFLAGS = ("-force_load", "$(PROJECT_DIR)/libmygo.a", "-framework", UIKit, "-framework", Foundation, "-framework", QuartzCore, "-framework", CoreGraphics, "-framework", CoreText, "-framework", Metal, "-framework", IOSurface, "-framework", AVFoundation, "-framework", Photos, "-framework", PhotosUI, "-framework", UniformTypeIdentifiers, "-framework", CoreLocation, "-framework", UserNotifications, "-framework", Security, "-framework", LocalAuthentication, "-lresolv");`, strconv.Quote(c.Identifier), strconv.Quote(minimum), strconv.Quote(team))
	if c.IOS.Signing.Style == "manual" {
		settings = strings.Replace(settings, "CODE_SIGN_STYLE = Automatic;", "CODE_SIGN_STYLE = Manual; PROVISIONING_PROFILE_SPECIFIER = "+strconv.Quote(c.IOS.Signing.ProvisioningProfile)+";", 1)
	}
	if c.IOS.Signing.Identity != "" {
		settings = strings.Replace(settings, `CODE_SIGN_IDENTITY = "Apple Development";`, "CODE_SIGN_IDENTITY = "+strconv.Quote(c.IOS.Signing.Identity)+";", 1)
	}

	// Ordinary xcodebuild builds do not enable deployment postprocessing by
	// default. Let Xcode collect the dSYM, strip local symbols, then sign the
	// app for both Release build and archive actions. Keep exported symbols.
	releaseSettings := strings.Replace(settings, "STRIP_INSTALLED_PRODUCT = NO;", "STRIP_INSTALLED_PRODUCT = YES; DEPLOYMENT_POSTPROCESSING = YES; STRIP_STYLE = non-global;", 1)

	return `// !$*UTF8*$!
{ archiveVersion = 1; classes = {}; objectVersion = 56; objects = {
 A00000000000000000000001 = {isa = PBXProject; buildConfigurationList = A00000000000000000000002; compatibilityVersion = "Xcode 14.0"; mainGroup = A00000000000000000000003; productRefGroup = A00000000000000000000004; targets = (A00000000000000000000005); };
 A00000000000000000000002 = {isa = XCConfigurationList; buildConfigurations = (A00000000000000000000006, A00000000000000000000022); defaultConfigurationIsVisible = 0; defaultConfigurationName = Debug; };
 A00000000000000000000003 = {isa = PBXGroup; children = (A00000000000000000000007, A00000000000000000000008, A00000000000000000000016, A00000000000000000000017, A00000000000000000000024` + iconGroup + `, A00000000000000000000004); sourceTree = "<group>"; };
 A00000000000000000000004 = {isa = PBXGroup; children = (A00000000000000000000009); name = Products; sourceTree = "<group>"; };
 A00000000000000000000005 = {isa = PBXNativeTarget; name = MyGoApp; productName = MyGoApp; productReference = A00000000000000000000009; productType = "com.apple.product-type.application"; buildConfigurationList = A00000000000000000000010; buildPhases = (A00000000000000000000011, A00000000000000000000012); buildRules = (); dependencies = (); };
 A00000000000000000000006 = {isa = XCBuildConfiguration; name = Debug; buildSettings = {SDKROOT = iphoneos;}; };
 A00000000000000000000007 = {isa = PBXFileReference; path = main.m; sourceTree = "<group>"; lastKnownFileType = sourcecode.c.objc; };
 A00000000000000000000008 = {isa = PBXFileReference; path = MyGoResources; sourceTree = "<group>"; lastKnownFileType = folder; };
 A00000000000000000000009 = {isa = PBXFileReference; path = MyGoApp.app; sourceTree = BUILT_PRODUCTS_DIR; explicitFileType = wrapper.application; };
 A00000000000000000000010 = {isa = XCConfigurationList; buildConfigurations = (A00000000000000000000013, A00000000000000000000023); defaultConfigurationIsVisible = 0; defaultConfigurationName = Debug; };
 A00000000000000000000011 = {isa = PBXSourcesBuildPhase; buildActionMask = 2147483647; files = (A00000000000000000000014); runOnlyForDeploymentPostprocessing = 0; };
 A00000000000000000000012 = {isa = PBXResourcesBuildPhase; buildActionMask = 2147483647; files = (A00000000000000000000015, A00000000000000000000018, A00000000000000000000019, A00000000000000000000025` + iconBuild + `); runOnlyForDeploymentPostprocessing = 0; };
 A00000000000000000000013 = {isa = XCBuildConfiguration; name = Debug; buildSettings = {` + settings + iconSetting + `}; };
 A00000000000000000000014 = {isa = PBXBuildFile; fileRef = A00000000000000000000007; };
 A00000000000000000000015 = {isa = PBXBuildFile; fileRef = A00000000000000000000008; };
 A00000000000000000000016 = {isa = PBXFileReference; path = LaunchScreen.storyboard; sourceTree = "<group>"; lastKnownFileType = file.storyboard; };
 A00000000000000000000017 = {isa = PBXFileReference; path = LaunchLogo.png; sourceTree = "<group>"; lastKnownFileType = image.png; };
 A00000000000000000000018 = {isa = PBXBuildFile; fileRef = A00000000000000000000016; };
 A00000000000000000000019 = {isa = PBXBuildFile; fileRef = A00000000000000000000017; };
 A00000000000000000000022 = {isa = XCBuildConfiguration; name = Release; buildSettings = {SDKROOT = iphoneos;}; };
 A00000000000000000000023 = {isa = XCBuildConfiguration; name = Release; buildSettings = {` + releaseSettings + iconSetting + `}; };
 A00000000000000000000024 = {isa = PBXFileReference; path = PrivacyInfo.xcprivacy; sourceTree = "<group>"; lastKnownFileType = text.xml; };
 A00000000000000000000025 = {isa = PBXBuildFile; fileRef = A00000000000000000000024; };
` + iconObjects + ` }; rootObject = A00000000000000000000001; }
`
}
