//go:build ios && cgo

#import "native.h"
#import "_cgo_export.h"
#import <CoreGraphics/CoreGraphics.h>
#import <QuartzCore/QuartzCore.h>
#import <UIKit/UIKit.h>
#import <Metal/Metal.h>
#import <PhotosUI/PhotosUI.h>
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#include <math.h>

// A strong export generated in the application's main package overrides
// this fallback. Keeping a weak definition also lets plain `go build`
// type-check and link packages without the CLI's hosted-entry overlay.
__attribute__((weak)) void MyGoIOSMain(void) {
  NSLog(@"MyGo iOS requires the entry generated by mygo build -platform "
        @"ios/arm64");
}
@class MyGoSurface;
static UIWindow *hostWindow;
static MyGoSurface *hostSurface;
static BOOL goReady, goStarted, sceneActive;
static int initialLifecycle;
static NSMutableArray<NSURL *> *pendingURLs;
static NSMutableArray<NSURL *> *pendingFiles;
static void cancelPresentations(void);
static BOOL interactiveKeyboardTracking(void);
static void lifecycle(int event) {
  if (event == 0 || event == 1 || event == 5) initialLifecycle = event;
  if (goReady) goIOSLifecycle(event);
}
static void openURL(NSURL *url) {
  if (!url) return;
  if (!goReady) {
    if (url.isFileURL) {
      if (!pendingFiles) pendingFiles = [NSMutableArray array];
      [pendingFiles addObject:url];
    } else {
      if (!pendingURLs) pendingURLs = [NSMutableArray array];
      [pendingURLs addObject:url];
    }
    return;
  }
  if (url.isFileURL) {
    BOOL access = [url startAccessingSecurityScopedResource];
    goIOSFile((char *)url.path.UTF8String);
    if (access) [url stopAccessingSecurityScopedResource];
  }
  else goIOSURL((char *)url.absoluteString.UTF8String);
}
static uint64_t nextTouchID;
static NSString *explicitStatusStyle;
static BOOL explicitStatusHidden;
static UIUserInterfaceStyle appearance = UIUserInterfaceStyleUnspecified;
static NSString *str(const char *s) {
  return s ? [NSString stringWithUTF8String:s] ?: @"" : @"";
}
static int runes(NSString *s) {
  int n = 0;
  for (NSUInteger i = 0; i < s.length; i++, n++) {
    unichar c = [s characterAtIndex:i];
    if (CFStringIsSurrogateHighCharacter(c) && i + 1 < s.length &&
        CFStringIsSurrogateLowCharacter([s characterAtIndex:i + 1]))
      i++;
  }
  return n;
}
static NSUInteger units(NSString *s, int n) {
  NSUInteger i = 0;
  for (int r = 0; r < n && i < s.length; r++, i++) {
    if (CFStringIsSurrogateHighCharacter([s characterAtIndex:i]) &&
        i + 1 < s.length &&
        CFStringIsSurrogateLowCharacter([s characterAtIndex:i + 1]))
      i++;
  }
  return i;
}

static NSArray<UIKeyCommand *> *hardwareCommands(void) {
  static NSArray<UIKeyCommand *> *commands;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    NSMutableArray *keys = [NSMutableArray array];
    for (NSString *input in @[@"\t", UIKeyInputEscape, @"a", @"c", @"x", @"v", @"z"]) {
      UIKeyModifierFlags mods = [input isEqual:@"\t"] || [input isEqual:UIKeyInputEscape] ? 0 : UIKeyModifierCommand;
      UIKeyCommand *key = [UIKeyCommand keyCommandWithInput:input modifierFlags:mods action:@selector(mygoHardwareCommand:)];
      key.wantsPriorityOverSystemBehavior = YES;
      [keys addObject:key];
      if ([input isEqual:@"\t"] || [input isEqual:@"z"]) {
        UIKeyCommand *shift = [UIKeyCommand keyCommandWithInput:input modifierFlags:mods|UIKeyModifierShift action:@selector(mygoHardwareCommand:)];
        shift.wantsPriorityOverSystemBehavior = YES;
        [keys addObject:shift];
      }
    }
    commands = keys.copy;
  });
  return commands;
}
static void hardwareCommand(uint64_t window, UIKeyCommand *key) {
  BOOL shift = (key.modifierFlags & UIKeyModifierShift) != 0;
  NSString *command = [key.input isEqual:@"\t"] ? (shift ? @"backtab" : @"tab") :
    [key.input isEqual:UIKeyInputEscape] ? @"escape" :
    [key.input isEqual:@"\r"] ? @"enter" : [key.input isEqual:@" "] ? @"space" :
    [key.input isEqual:@"a"] ? @"selectAll" : [key.input isEqual:@"c"] ? @"copy" :
    [key.input isEqual:@"x"] ? @"cut" : [key.input isEqual:@"v"] ? @"paste" : shift ? @"redo" : @"undo";
  goIOSHardwareCommand(window, (char *)command.UTF8String);
}
static UIKeyCommand *hardwarePressCommand(UIKey *key, BOOL surface) {
  if (!key) return nil;
  NSString *input = key.charactersIgnoringModifiers.lowercaseString;
  if (key.keyCode == UIKeyboardHIDUsageKeyboardTab) input = @"\t";
  if (key.keyCode == UIKeyboardHIDUsageKeyboardEscape) input = UIKeyInputEscape;
  UIKeyModifierFlags mods = key.modifierFlags & (UIKeyModifierShift|UIKeyModifierControl|UIKeyModifierAlternate|UIKeyModifierCommand);
  for (UIKeyCommand *command in hardwareCommands())
    if ([command.input isEqual:input] && command.modifierFlags == mods) return command;
  if (surface && mods == 0 && (key.keyCode == UIKeyboardHIDUsageKeyboardReturnOrEnter || key.keyCode == UIKeyboardHIDUsageKeyboardSpacebar))
    return [UIKeyCommand keyCommandWithInput:key.keyCode == UIKeyboardHIDUsageKeyboardSpacebar ? @" " : @"\r" modifierFlags:0 action:@selector(mygoHardwareCommand:)];
  return nil;
}
static NSSet<UIPress *> *remainingHardwarePresses(NSSet<UIPress *> *presses, NSMutableSet<NSNumber *> *handled) {
  NSMutableSet *remaining = [NSMutableSet set];
  for (UIPress *press in presses) {
    NSNumber *code = @(press.key.keyCode);
    if ([handled containsObject:code]) [handled removeObject:code];
    else [remaining addObject:press];
  }
  return remaining;
}

@interface MyGoAccess : UIAccessibilityElement
@property(nonatomic) uint64_t windowID;
@property(nonatomic) uint64_t nodeID;
@property(nonatomic) unsigned actions;
@end
@implementation MyGoAccess
- (BOOL)accessibilityActivate {
  return goIOSAccess(self.windowID, self.nodeID, (self.actions & 1) ? 0 : 1);
}
- (void)accessibilityIncrement {
  goIOSAccess(self.windowID, self.nodeID, 2);
}
- (void)accessibilityDecrement {
  goIOSAccess(self.windowID, self.nodeID, 3);
}
- (void)accessibilityElementDidBecomeFocused {
  goIOSAccess(self.windowID, self.nodeID, 1);
}
@end

@class MyGoEditor;
@interface MyGoUndoManager : NSUndoManager
@property(nonatomic, weak) MyGoEditor *editor;
@end
@interface MyGoEditor : UITextView <UITextSelectionDisplayInteractionDelegate>
@property(nonatomic) uint64_t windowID;
@property(nonatomic) uint64_t fieldID;
@property(nonatomic) BOOL multiline;
@property(nonatomic) CGRect goAccessibilityFrame;
@property(nonatomic) CGRect goCaret;
@property(nonatomic, strong) NSMutableSet<NSNumber *> *hardwareKeys;
@property(nonatomic, strong) MyGoUndoManager *goUndoManager;
@property(nonatomic) BOOL goCanUndo, goCanRedo;
@property(nonatomic, copy) NSString *accessoryJSON;
@property(nonatomic, strong) UITextSelectionDisplayInteraction *selectionDisplay API_AVAILABLE(ios(17.0));
@end

// Native buttons stay outside the Go focus chain. Expanding secondary keys
// preserves the same UITextView and its marked-text/candidate session.
@interface MyGoInputAccessory : UIInputView
@property(nonatomic) uint64_t windowID, ownerID;
@property(nonatomic, weak) MyGoEditor *editor;
@property(nonatomic, strong) NSArray *actions;
@property(nonatomic, strong) UIStackView *stack;
@property(nonatomic, strong) NSLayoutConstraint *height;
@property(nonatomic) BOOL expanded;
@end
@implementation MyGoInputAccessory
- (instancetype)init {
 self=[super initWithFrame:CGRectMake(0,0,390,44) inputViewStyle:UIInputViewStyleKeyboard];
 if (self) {
  self.allowsSelfSizing=YES;
  self.autoresizingMask=UIViewAutoresizingFlexibleHeight;
  self.height=[self.heightAnchor constraintEqualToConstant:44];
  self.height.active=YES;
  self.backgroundColor=UIColor.secondarySystemBackgroundColor;
  self.accessibilityIdentifier=@"Input accessory";
 }
 return self;
}
- (CGSize)intrinsicContentSize {
 NSUInteger count=0;
 if (self.expanded) for (NSDictionary *action in self.actions) count+= [action[@"Items"] count];
 return CGSizeMake(UIViewNoIntrinsicMetric,44+(count ? ceil(count/5.0)*44+8 : 0));
}
- (CGSize)systemLayoutSizeFittingSize:(CGSize)targetSize {
 return CGSizeMake(targetSize.width,self.intrinsicContentSize.height);
}
- (CGSize)systemLayoutSizeFittingSize:(CGSize)targetSize withHorizontalFittingPriority:(UILayoutPriority)horizontalFittingPriority verticalFittingPriority:(UILayoutPriority)verticalFittingPriority {
 return [self systemLayoutSizeFittingSize:targetSize];
}
- (UIButton *)button:(NSDictionary *)action {
 UIButton *button=[UIButton buttonWithType:UIButtonTypeSystem];
 button.accessibilityLabel=action[@"Label"];
 button.accessibilityIdentifier=action[@"Label"];
 NSString *symbol=action[@"Symbol"];
 UIImage *image=symbol.length ? [UIImage systemImageNamed:symbol] : nil;
 if (image) [button setImage:[image imageWithConfiguration:[UIImageSymbolConfiguration configurationWithPointSize:18 weight:UIImageSymbolWeightRegular]] forState:UIControlStateNormal];
 else [button setTitle:action[@"Label"] forState:UIControlStateNormal];
 button.titleLabel.font=[UIFont systemFontOfSize:14 weight:UIFontWeightMedium];
 button.tintColor=UIColor.labelColor;
 __weak MyGoInputAccessory *weakSelf=self;
 [button addAction:[UIAction actionWithHandler:^(UIAction *event) {
  MyGoInputAccessory *accessory=weakSelf;
  if (!accessory) return;
  if ([action[@"Items"] count]) {
   accessory.expanded=!accessory.expanded;
   [accessory rebuild];
   // UIKit caches the accessory's height. Reload its layout without changing
   // first responder or replacing the editor's marked-text session.
   [accessory.editor reloadInputViews];
  } else goIOSInputAction(accessory.windowID,accessory.ownerID,(char *)[action[@"ID"] UTF8String]);
 }] forControlEvents:UIControlEventTouchUpInside];
 if ([action[@"Items"] count] && self.expanded) {
  button.backgroundColor=UIColor.tertiarySystemFillColor;
  button.layer.cornerRadius=8;
  button.accessibilityValue=@"已展开";
 }
 return button;
}
- (UIStackView *)row:(NSArray *)actions columns:(NSUInteger)columns {
 UIStackView *row=[UIStackView new];
 row.axis=UILayoutConstraintAxisHorizontal;
 row.distribution=UIStackViewDistributionFillEqually;
 row.spacing=2;
 for (NSDictionary *action in actions) [row addArrangedSubview:[self button:action]];
 while (row.arrangedSubviews.count<columns) [row addArrangedSubview:[UIView new]];
 [row.heightAnchor constraintEqualToConstant:44].active=YES;
 return row;
}
- (void)rebuild {
 [self.stack removeFromSuperview];
 UIStackView *stack=[UIStackView new];
 self.stack=stack;
 stack.axis=UILayoutConstraintAxisVertical;
 stack.translatesAutoresizingMaskIntoConstraints=NO;
 if (self.expanded) {
  NSMutableArray *items=[NSMutableArray array];
  for (NSDictionary *action in self.actions) [items addObjectsFromArray:action[@"Items"] ?: @[]];
  for (NSUInteger i=0;i<items.count;i+=5) [stack addArrangedSubview:[self row:[items subarrayWithRange:NSMakeRange(i,MIN(5,items.count-i))] columns:5]];
  if (items.count) {
   UIView *gap=[UIView new];
   [gap.heightAnchor constraintEqualToConstant:8].active=YES;
   [stack addArrangedSubview:gap];
  }
 }
 [stack addArrangedSubview:[self row:self.actions columns:self.actions.count]];
 [self addSubview:stack];
 [NSLayoutConstraint activateConstraints:@[
  [stack.leadingAnchor constraintEqualToAnchor:self.safeAreaLayoutGuide.leadingAnchor constant:8],
  [stack.trailingAnchor constraintEqualToAnchor:self.safeAreaLayoutGuide.trailingAnchor constant:-8],
  [stack.topAnchor constraintEqualToAnchor:self.topAnchor],
  [stack.bottomAnchor constraintEqualToAnchor:self.bottomAnchor]
 ]];
 self.height.constant=self.intrinsicContentSize.height;
 CGRect frame=self.frame;frame.size.height=self.height.constant;self.frame=frame;
 [self invalidateIntrinsicContentSize];
 [self setNeedsLayout];
 [self.superview setNeedsLayout];
}
@end
@implementation MyGoUndoManager
- (BOOL)canUndo { return self.editor.editable && self.editor.goCanUndo; }
- (BOOL)canRedo { return self.editor.editable && self.editor.goCanRedo; }
- (void)undo { if (self.canUndo) goIOSEditCommand(self.editor.windowID, "undo"); }
- (void)redo { if (self.canRedo) goIOSEditCommand(self.editor.windowID, "redo"); }
@end

// UITextView supplies system handles and editing gestures; their geometry
// comes from the Go layout rather than TextKit's transparent proxy text.
@interface MyGoSelectionRect : UITextSelectionRect
@property(nonatomic) CGRect goRect;
@property(nonatomic) BOOL start, end;
@property(nonatomic) NSWritingDirection direction;
@end
@implementation MyGoSelectionRect
- (CGRect)rect { return self.goRect; }
- (NSWritingDirection)writingDirection { return self.direction; }
- (BOOL)containsStart { return self.start; }
- (BOOL)containsEnd { return self.end; }
- (BOOL)isVertical { return NO; }
@end

@implementation MyGoEditor
- (NSUndoManager *)undoManager {
  if (!self.goUndoManager) {
    self.goUndoManager = [MyGoUndoManager new];
    self.goUndoManager.editor = self;
    self.goUndoManager.levelsOfUndo = 1;
  }
  return self.goUndoManager;
}
- (void)pressesBegan:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event {
  NSMutableSet *remaining = [NSMutableSet set];
  if (!self.hardwareKeys) self.hardwareKeys = [NSMutableSet set];
  for (UIPress *press in presses) {
    UIKeyCommand *command = self.markedTextRange ? nil : hardwarePressCommand(press.key, NO);
    if (command) { [self.hardwareKeys addObject:@(press.key.keyCode)]; [self mygoHardwareCommand:command]; }
    else [remaining addObject:press];
  }
  if (remaining.count) [super pressesBegan:remaining withEvent:event];
}
- (void)pressesEnded:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event {
  NSSet *remaining = remainingHardwarePresses(presses, self.hardwareKeys);
  if (remaining.count) [super pressesEnded:remaining withEvent:event];
}
- (void)pressesCancelled:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event {
  NSSet *remaining = remainingHardwarePresses(presses, self.hardwareKeys);
  if (remaining.count) [super pressesCancelled:remaining withEvent:event];
}
- (NSArray<UIKeyCommand *> *)keyCommands {
  // Let the input method handle candidate navigation/cancellation first.
  return self.markedTextRange ? super.keyCommands : hardwareCommands();
}
- (void)mygoHardwareCommand:(UIKeyCommand *)key {
  if (self.secureTextEntry && ([@[@"a", @"c", @"x"] containsObject:key.input])) return;
  if (!self.editable && ([@[@"x", @"v", @"z"] containsObject:key.input])) return;
  hardwareCommand(self.windowID, key);
  [UIMenuController.sharedMenuController hideMenuFromView:self];
}
- (UIView *)textInputView { return self; }
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event {
  if ([super pointInside:point withEvent:event]) return YES;
  if (@available(iOS 17.0, *)) {
    if (self.fieldID && !self.secureTextEntry && self.selectedRange.length) {
      for (UIView *handle in self.selectionDisplay.handleViews)
        if (handle.superview && !handle.hidden && CGRectContainsPoint(CGRectInset([self convertRect:handle.bounds fromView:handle], -5, -5), point)) return YES;
    }
  }
  return NO;
}
// Go scrolls the editor and its ancestors. TextKit's invisible layout must
// not move the proxy or selection handles independently of those layouts.
- (void)setContentOffset:(CGPoint)offset { [super setContentOffset:CGPointZero]; }
- (void)setContentOffset:(CGPoint)offset animated:(BOOL)animated { [super setContentOffset:CGPointZero animated:NO]; }
- (void)scrollRangeToVisible:(NSRange)range {}
- (void)scrollRectToVisible:(CGRect)rect animated:(BOOL)animated {}
- (NSDictionary *)geometry:(const char *)kind from:(NSInteger)start to:(NSInteger)end point:(CGPoint)point {
  if (!self.fieldID || self.secureTextEntry || self.markedTextRange) return nil;
  start = MAX(0, MIN(start, (NSInteger)self.text.length));
  end = MAX(0, MIN(end, (NSInteger)self.text.length));
  CGPoint p = [self convertPoint:point toView:self.superview];
  char *json = goIOSTextGeometry(self.windowID, self.fieldID, (char *)kind,
      runes([self.text substringToIndex:start]), runes([self.text substringToIndex:end]), p.x, p.y);
  NSData *data = [str(json) dataUsingEncoding:NSUTF8StringEncoding];
  free(json);
  NSDictionary *g = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
  return [g[@"Valid"] boolValue] ? g : nil;
}
- (CGRect)localRect:(NSDictionary *)r {
  return [self convertRect:CGRectMake([r[@"X"] doubleValue], [r[@"Y"] doubleValue],
      [r[@"W"] doubleValue], [r[@"H"] doubleValue]) fromView:self.superview];
}
- (CGRect)caretRectForPosition:(UITextPosition *)position {
  NSInteger i = [self offsetFromPosition:self.beginningOfDocument toPosition:position];
  NSDictionary *g = [self geometry:"caret" from:i to:i point:CGPointZero];
  return g ? [self localRect:g[@"Caret"]] :
      ((self.secureTextEntry || !self.fieldID || self.markedTextRange)
        ? [self convertRect:self.goCaret fromView:self.superview] : CGRectZero);
}
- (NSArray<UITextSelectionRect *> *)selectionRectsForRange:(UITextRange *)range {
  NSInteger a = [self offsetFromPosition:self.beginningOfDocument toPosition:range.start];
  NSInteger z = [self offsetFromPosition:self.beginningOfDocument toPosition:range.end];
  NSDictionary *g = [self geometry:"selection" from:a to:z point:CGPointZero];
  if (!g) return @[];
  CGRect first = [self caretRectForPosition:range.start], last = [self caretRectForPosition:range.end];
  NSMutableArray *out = [NSMutableArray array];
  NSArray *rects = [g[@"Rects"] isKindOfClass:NSArray.class] ? g[@"Rects"] : @[];
  for (NSDictionary *r in rects) {
    MyGoSelectionRect *s = [MyGoSelectionRect new];
    s.goRect = [self localRect:r];
    s.direction = [r[@"RTL"] boolValue] ? NSWritingDirectionRightToLeft : NSWritingDirectionLeftToRight;
    s.start = CGRectContainsPoint(CGRectInset(s.goRect, -1, -1), CGPointMake(CGRectGetMinX(first), CGRectGetMidY(first)));
    s.end = CGRectContainsPoint(CGRectInset(s.goRect, -1, -1), CGPointMake(CGRectGetMinX(last), CGRectGetMidY(last)));
    [out addObject:s];
  }
  return out;
}
- (CGRect)firstRectForRange:(UITextRange *)range {
  NSArray<UITextSelectionRect *> *rects = [self selectionRectsForRange:range];
  return rects.count ? rects.firstObject.rect : [self caretRectForPosition:range.start];
}
- (UITextPosition *)closestPositionToPoint:(CGPoint)point {
  NSDictionary *g = [self geometry:"hit" from:0 to:0 point:point];
  if (!g) return self.selectedTextRange.end ?: self.beginningOfDocument;
  return [self positionFromPosition:self.beginningOfDocument offset:units(self.text, [g[@"Index"] intValue])];
}
- (UITextPosition *)closestPositionToPoint:(CGPoint)point withinRange:(UITextRange *)range {
  UITextPosition *p = [self closestPositionToPoint:point];
  if ([self comparePosition:p toPosition:range.start] == NSOrderedAscending) return range.start;
  if ([self comparePosition:p toPosition:range.end] == NSOrderedDescending) return range.end;
  return p;
}
- (UITextRange *)characterRangeAtPoint:(CGPoint)point {
  UITextPosition *p = [self closestPositionToPoint:point];
  return [self.tokenizer rangeEnclosingPosition:p withGranularity:UITextGranularityCharacter inDirection:UITextStorageDirectionForward];
}
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender {
  if (action == @selector(undoManager)) return YES;
  if (action == @selector(mygoHardwareCommand:)) {
    if (self.markedTextRange) return NO;
    if (![sender isKindOfClass:UIKeyCommand.class]) return YES;
    NSString *input = ((UIKeyCommand *)sender).input;
    if ([input isEqual:@"\t"] || [input isEqual:UIKeyInputEscape]) return YES;
    if ([input isEqual:@"v"]) return self.editable && UIPasteboard.generalPasteboard.hasStrings;
    if ([input isEqual:@"z"]) return self.editable;
    if (self.secureTextEntry) return NO;
    if ([input isEqual:@"x"] && !self.editable) return NO;
    return YES;
  }
  if (action == @selector(paste:)) return self.editable && UIPasteboard.generalPasteboard.hasStrings;
  if (action == @selector(cut:) && !self.editable) return NO;
  if (self.secureTextEntry) return NO;
  if (action == @selector(copy:) || action == @selector(cut:))
    return self.selectedRange.length > 0;
  if (action == @selector(select:)) return self.text.length > 0 && self.selectedRange.length == 0;
  if (action == @selector(selectAll:)) return self.text.length > self.selectedRange.length;
  return NO;
}
- (void)copy:(id)sender { goIOSEditCommand(self.windowID, "copy"); [UIMenuController.sharedMenuController hideMenuFromView:self]; }
- (void)cut:(id)sender { goIOSEditCommand(self.windowID, "cut"); [UIMenuController.sharedMenuController hideMenuFromView:self]; }
- (void)paste:(id)sender { goIOSEditCommand(self.windowID, "paste"); [UIMenuController.sharedMenuController hideMenuFromView:self]; }
- (void)selectAll:(id)sender {
  if (self.secureTextEntry) return;
  goIOSEditCommand(self.windowID, "selectAll");
  uint64_t field = self.fieldID;
  dispatch_async(dispatch_get_main_queue(), ^{
    if (self.isFirstResponder && self.fieldID == field)
      [UIMenuController.sharedMenuController showMenuFromView:self rect:[self firstRectForRange:self.selectedTextRange]];
  });
}
- (void)delete:(id)sender { goIOSEditCommand(self.windowID, "delete"); [UIMenuController.sharedMenuController hideMenuFromView:self]; }
- (CGRect)accessibilityFrame {
  return self.isAccessibilityElement ? self.goAccessibilityFrame
                                     : [super accessibilityFrame];
}
- (void)insertText:(NSString *)text {
 if (!self.editable) return;
  if (!self.multiline && [text isEqual:@"\n"]) {
    goIOSText(self.windowID, 5, NULL, 0, 0, 0);
    goIOSInputSync(self.windowID);
    return;
  }
  if (!self.secureTextEntry) {
    [super insertText:text];
    return;
  }
  goIOSText(self.windowID, [text isEqual:@"\n"] ? 5 : 3,
            (char *)text.UTF8String, 0, 0, 0);
  goIOSInputSync(self.windowID);
}
- (BOOL)hasText {
  // A custom widget (terminal) owns its text outside this empty UIKit proxy.
  if (!self.fieldID && self.editable && self.isFirstResponder) return YES;
  return super.hasText;
}
- (void)deleteBackward {
 if (!self.editable) return;
  if (!self.secureTextEntry && (self.fieldID || self.markedTextRange)) {
    [super deleteBackward];
    return;
  }
  goIOSText(self.windowID, 4, NULL, 0, 0, 0);
  goIOSInputSync(self.windowID);
}
@end

@interface MyGoSurface : UIView <UITextViewDelegate, UIGestureRecognizerDelegate>
@property(nonatomic) uint64_t windowID;
@property(nonatomic, strong) CADisplayLink *displayLink;
@property(nonatomic, strong) UITextView *editor;
@property(nonatomic, strong) UITouch *contact;
@property(nonatomic) uint64_t contactID;
@property(nonatomic) CGPoint origin;
@property(nonatomic) CGPoint previous;
@property(nonatomic) CGPoint velocity;
@property(nonatomic) NSTimeInterval previousTime;
@property(nonatomic) BOOL scrolling;
@property(nonatomic) CGSize reportedSize;
@property(nonatomic) CGFloat reportedScale;
@property(nonatomic) BOOL framePending;
@property(nonatomic) BOOL sending;
@property(nonatomic) BOOL syncing;
@property(nonatomic) int contextLength;
@property(nonatomic, copy) NSString *synchronizedText;
@property(nonatomic) NSTimeInterval lastTick;
@property(nonatomic) BOOL accessibilityStarted;
@property(nonatomic) BOOL firstPresented;
@property(nonatomic) BOOL presentationQueued;
@property(nonatomic) NSUInteger presentationGeneration;
@property(nonatomic, strong) NSMutableSet<NSNumber *> *hardwareKeys;
@property(nonatomic, strong) NSArray *goAccessibilityElements;
- (void)commitText;
@end
@implementation MyGoSurface
- (void)pressesBegan:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event {
  NSMutableSet *remaining = [NSMutableSet set];
  if (!self.hardwareKeys) self.hardwareKeys = [NSMutableSet set];
  for (UIPress *press in presses) {
    UIKeyCommand *command = self.editor.markedTextRange ? nil : hardwarePressCommand(press.key, YES);
    if (command) { [self.hardwareKeys addObject:@(press.key.keyCode)]; [self mygoHardwareCommand:command]; }
    else [remaining addObject:press];
  }
  if (remaining.count) [super pressesBegan:remaining withEvent:event];
}
- (void)pressesEnded:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event {
  NSSet *remaining = remainingHardwarePresses(presses, self.hardwareKeys);
  if (remaining.count) [super pressesEnded:remaining withEvent:event];
}
- (void)pressesCancelled:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event {
  NSSet *remaining = remainingHardwarePresses(presses, self.hardwareKeys);
  if (remaining.count) [super pressesCancelled:remaining withEvent:event];
}
- (BOOL)canBecomeFirstResponder { return YES; }
- (NSArray<UIKeyCommand *> *)keyCommands {
  if (self.editor.isFirstResponder) return nil;
  NSMutableArray *commands = hardwareCommands().mutableCopy;
  for (NSString *input in @[@"\r", @" "])
    [commands addObject:[UIKeyCommand keyCommandWithInput:input modifierFlags:0 action:@selector(mygoHardwareCommand:)]];
  return commands;
}
- (void)mygoHardwareCommand:(UIKeyCommand *)key { hardwareCommand(self.windowID, key); }
- (instancetype)initWithFrame:(CGRect)frame {
  if ((self = [super initWithFrame:frame])) {
    self.multipleTouchEnabled = YES;
    self.clipsToBounds = YES;
    self.backgroundColor = UIColor.systemBackgroundColor;
    self.displayLink = [CADisplayLink displayLinkWithTarget:self
                                                   selector:@selector(tick:)];
    self.displayLink.paused = YES;
    [self.displayLink addToRunLoop:NSRunLoop.mainRunLoop
                           forMode:NSRunLoopCommonModes];
    self.editor = [[MyGoEditor alloc] initWithFrame:CGRectZero];
    self.editor.delegate = self;
    self.editor.backgroundColor = UIColor.clearColor;
    self.editor.textColor = UIColor.clearColor;
    self.editor.tintColor = UIColor.clearColor;
    self.editor.scrollEnabled = NO;
    self.editor.clipsToBounds = NO;
    // Metal is added to the surface after this proxy. Keep UIKit's
    // selection visuals above the opaque renderer regardless of insertion order.
    self.editor.layer.zPosition = 1;
    self.editor.showsVerticalScrollIndicator = NO;
    self.editor.showsHorizontalScrollIndicator = NO;
    self.editor.userInteractionEnabled = YES;
    self.editor.isAccessibilityElement = NO;
    self.editor.textContainerInset = UIEdgeInsetsZero;
    if (@available(iOS 17.0, *)) {
      MyGoEditor *e = (MyGoEditor *)self.editor;
      for (id<UIInteraction> i in e.interactions.copy)
        if ([i isKindOfClass:UITextSelectionDisplayInteraction.class]) [e removeInteraction:i];
      e.selectionDisplay = [[UITextSelectionDisplayInteraction alloc] initWithTextInput:e delegate:e];
      e.selectionDisplay.activated = NO;
      [e addInteraction:e.selectionDisplay];
    }
    [self addSubview:self.editor];
    UILongPressGestureRecognizer *select = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(selectText:)];
    select.cancelsTouchesInView = NO;
    select.delegate = self;
    [self addGestureRecognizer:select];
    UIPanGestureRecognizer *scroll = [[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(scrollText:)];
    scroll.delegate = self;
    [self addGestureRecognizer:scroll];
 UIPinchGestureRecognizer *pinch=[[UIPinchGestureRecognizer alloc] initWithTarget:self action:@selector(multiGesture:)];pinch.delegate=self;[self addGestureRecognizer:pinch];
 UIRotationGestureRecognizer *rotate=[[UIRotationGestureRecognizer alloc] initWithTarget:self action:@selector(multiGesture:)];rotate.delegate=self;[self addGestureRecognizer:rotate];
  }
  return self;
}
- (void)layoutSubviews {
  [super layoutSubviews];
  // Editing proxy/selection subviews can relayout the surface without
  // changing its size. A synthetic resize would cancel Go's back preview.
  CGFloat scale = self.window.screen.scale;
  if (self.windowID && (!CGSizeEqualToSize(self.reportedSize, self.bounds.size) || self.reportedScale != scale)) {
    self.reportedSize = self.bounds.size;
    self.reportedScale = scale;
    goIOSResize(self.windowID);
  }
  [self requestFrame];
}
// Only the focused editable field receives UIKit selection gestures. Go
// continues handling other widgets, scrolling and the reserved back edge.
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
  UIView *hit = [super hitTest:point withEvent:event];
  if ([hit isDescendantOfView:self.editor] &&
      (!((MyGoEditor *)self.editor).fieldID || !self.editor.isFirstResponder || self.editor.secureTextEntry || point.x < 24)) return self;
  return hit;
}
- (void)selectText:(UILongPressGestureRecognizer *)gesture {
  if (gesture.state != UIGestureRecognizerStateBegan || !((MyGoEditor *)self.editor).fieldID || !self.editor.isFirstResponder) return;
  CGPoint p = [gesture locationInView:self];
  if (p.x < 24 || !CGRectContainsPoint(self.editor.frame, p)) return;
  if (self.contact) {
    goIOSTouch(self.windowID, self.contactID, 3, self.previous.x, self.previous.y);
    self.contact = nil;
  }
  self.velocity = CGPointZero;
  if (!self.editor.secureTextEntry) {
    UITextPosition *at = [self.editor closestPositionToPoint:[self convertPoint:p toView:self.editor]];
    UITextRange *word = [self.editor.tokenizer rangeEnclosingPosition:at withGranularity:UITextGranularityWord inDirection:UITextStorageDirectionForward];
    if (word) self.editor.selectedTextRange = word;
    else [self.editor select:self];
  }
  [UIMenuController.sharedMenuController showMenuFromView:self.editor rect:[self.editor firstRectForRange:self.editor.selectedTextRange]];
}
- (void)multiGesture:(UIGestureRecognizer *)gesture {
 BOOL pinch=[gesture isKindOfClass:UIPinchGestureRecognizer.class];
 CGPoint p=[gesture locationInView:self];
 const char *phase=gesture.state==UIGestureRecognizerStateBegan?"begin":gesture.state==UIGestureRecognizerStateChanged?"change":gesture.state==UIGestureRecognizerStateEnded?"end":"cancel";
 self.velocity=CGPointZero;
 goIOSGesture(self.windowID,(char *)(pinch?"pinch":"rotate"),(char *)phase,p.x,p.y,
 pinch?[(UIPinchGestureRecognizer *)gesture scale]:1,pinch?0:[(UIRotationGestureRecognizer *)gesture rotation]);
}
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gesture {
 // UIView also consults the hit view for recognizers attached to ancestors.
 // Restrict our editor-scroll decision to this surface's own recognizers.
 if (gesture.view != self) return [super gestureRecognizerShouldBegin:gesture];
 if ([gesture isKindOfClass:UIPinchGestureRecognizer.class] || [gesture isKindOfClass:UIRotationGestureRecognizer.class]) {
 CGPoint p=[gesture locationInView:self];
 return goIOSGesture(self.windowID,(char *)([gesture isKindOfClass:UIPinchGestureRecognizer.class]?"pinch":"rotate"),"probe",p.x,p.y,1,0);
 }
  if (![gesture isKindOfClass:UIPanGestureRecognizer.class]) return YES;
  CGPoint p = [gesture locationInView:self], v = [(UIPanGestureRecognizer *)gesture velocityInView:self];
  return ((MyGoEditor *)self.editor).fieldID && self.editor.isFirstResponder && !self.editor.secureTextEntry &&
      self.editor.selectedRange.length == 0 && p.x >= 24 &&
      CGRectContainsPoint(self.editor.frame, p) && fabs(v.y) > fabs(v.x);
}
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gesture shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)other {
  if (([gesture isKindOfClass:UIPinchGestureRecognizer.class] || [gesture isKindOfClass:UIRotationGestureRecognizer.class]) &&
      ([other isKindOfClass:UIPinchGestureRecognizer.class] || [other isKindOfClass:UIRotationGestureRecognizer.class])) return YES;
  return [gesture isKindOfClass:UILongPressGestureRecognizer.class] ||
      [other isKindOfClass:UILongPressGestureRecognizer.class];
}
- (void)scrollText:(UIPanGestureRecognizer *)gesture {
  if (gesture.state == UIGestureRecognizerStateBegan) {
    [self commitText];
    if (self.contact) {
      goIOSTouch(self.windowID, self.contactID, 3, self.previous.x, self.previous.y);
      self.contact = nil;
    }
    self.origin = [gesture locationInView:self];
    self.velocity = CGPointZero;
  }
  if (gesture.state == UIGestureRecognizerStateBegan || gesture.state == UIGestureRecognizerStateChanged) {
    CGPoint delta = [gesture translationInView:self];
    goIOSScroll(self.windowID, self.origin.x, self.origin.y, -delta.x, -delta.y);
    [gesture setTranslation:CGPointZero inView:self];
  } else if (gesture.state == UIGestureRecognizerStateEnded) {
    self.velocity = [gesture velocityInView:self];
    [self requestFrame];
  } else if (gesture.state == UIGestureRecognizerStateCancelled) {
    self.velocity = CGPointZero;
  }
}
- (void)traitCollectionDidChange:(UITraitCollection *)previous {
  [super traitCollectionDidChange:previous];
  if ([self.traitCollection
          hasDifferentColorAppearanceComparedToTraitCollection:previous])
    lifecycle(2);
}
- (NSArray *)accessibilityElements {
  if (!self.accessibilityStarted) {
    self.accessibilityStarted = YES;
    goIOSAccessibilityOn(self.windowID);
  }
  return self.goAccessibilityElements;
}
- (void)requestFrame {
  self.framePending = YES;
  if (sceneActive && self.window)
    self.displayLink.paused = NO;
}
- (void)tick:(CADisplayLink *)link {
  double dt =
      self.lastTick > 0 ? MIN(link.timestamp - self.lastTick, 0.05) : 1.0 / 60;
  self.lastTick = link.timestamp;
  if (!self.contact &&
      (fabs(self.velocity.x) > 5 || fabs(self.velocity.y) > 5)) {
    goIOSScroll(self.windowID, self.origin.x, self.origin.y,
                -self.velocity.x * dt, -self.velocity.y * dt);
    double decay = exp(-7 * dt);
    self.velocity =
        CGPointMake(self.velocity.x * decay, self.velocity.y * decay);
  }
  if (self.framePending) {
    self.framePending = NO;
    goIOSFrame(self.windowID);
  }
  if (!self.framePending &&
      (self.contact || hypot(self.velocity.x, self.velocity.y) < 5)) {
    self.displayLink.paused = YES;
    self.lastTick = 0;
  }
}
- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
  if (self.contact)
    return;
  // Commit before Go moves focus: UIKit's resignation notifications would
  // otherwise deliver a pending composition to the newly focused widget.
  [self commitText];
  self.contact = touches.anyObject;
  self.contactID = ++nextTouchID;
  self.origin = self.previous = [self.contact locationInView:self];
  self.previousTime = self.contact.timestamp;
  self.velocity = CGPointZero;
  self.scrolling = NO;
  goIOSTouch(self.windowID, self.contactID, 0, self.origin.x, self.origin.y);
}
- (void)touchesMoved:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
  if (!self.contact || ![touches containsObject:self.contact])
    return;
  CGPoint p = [self.contact locationInView:self];
  double dt = self.contact.timestamp - self.previousTime;
  if (dt > 0) {
    self.velocity =
        CGPointMake((p.x - self.previous.x) / dt, (p.y - self.previous.y) / dt);
  }
  self.scrolling = goIOSTouch(self.windowID, self.contactID, 1, p.x, p.y);
  self.previous = p;
  self.previousTime = self.contact.timestamp;
}
- (void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
  if (!self.contact || ![touches containsObject:self.contact])
    return;
  CGPoint p = [self.contact locationInView:self];
  goIOSTouch(self.windowID, self.contactID, 2, p.x, p.y);
  if (!self.scrolling || self.contact.timestamp - self.previousTime > 0.1)
    self.velocity = CGPointZero;
  self.contact = nil;
  if (self.scrolling)
    [self requestFrame];
}
- (void)touchesCancelled:(NSSet<UITouch *> *)touches
               withEvent:(UIEvent *)event {
  if (!self.contact || ![touches containsObject:self.contact])
    return;
  goIOSTouch(self.windowID, self.contactID, 3, self.previous.x,
             self.previous.y);
  self.contact = nil;
  self.velocity = CGPointZero;
}
- (void)textViewDidEndEditing:(UITextView *)textView {
 if (!self.syncing && !interactiveKeyboardTracking()) goIOSDismissKeyboard(self.windowID);
}
- (void)textViewDidChange:(UITextView *)textView {
  if (self.syncing)
    return;
  self.sending = YES;
  BOOL composing = textView.markedTextRange != nil;
  NSUInteger caret =
      MIN(NSMaxRange(textView.selectedRange), textView.text.length);
  if (composing && ((MyGoEditor *)textView).fieldID) {
    // UIKit's marked range is provisional; surrounding text is committed.
    // Reconcile both in one Go frame, including incremental candidate commits.
    // The sending/markedTextRange guards prevent echoing into UIKit.
    UITextRange *marked = textView.markedTextRange;
    NSUInteger start = [textView offsetFromPosition:textView.beginningOfDocument toPosition:marked.start];
    NSUInteger end = [textView offsetFromPosition:textView.beginningOfDocument toPosition:marked.end];
    goIOSComposition(self.windowID, (char *)textView.text.UTF8String,
      runes([textView.text substringToIndex:start]),
      runes([textView.text substringToIndex:end]),
      runes([textView.text substringToIndex:caret]));
  } else {
    goIOSText(self.windowID, composing ? 1 : 0, (char *)textView.text.UTF8String,
              0, self.contextLength,
              runes([textView.text substringToIndex:caret]));
  }
  self.sending = NO;
  goIOSInputSync(self.windowID);
}
- (void)commitText {
  if (self.editor.markedTextRange) {
    [self.editor unmarkText];
    [self textViewDidChange:self.editor];
  }
}
- (void)textViewDidChangeSelection:(UITextView *)textView {
  if (self.syncing || self.sending || textView.markedTextRange)
    return;
  // UIKit may report the selection moved by an insertion before it reports
  // the new text. Synchronizing the old Go value here would erase that edit.
  // textViewDidChange will deliver the text and its selection together.
  if (![textView.text isEqual:self.synchronizedText])
    return;
  NSUInteger start = MIN(textView.selectedRange.location, textView.text.length),
             end =
                 MIN(NSMaxRange(textView.selectedRange), textView.text.length);
  self.sending = YES;
  goIOSText(self.windowID, 2, NULL,
            runes([textView.text substringToIndex:start]),
            runes([textView.text substringToIndex:end]), 0);
  self.sending = NO;
  goIOSInputSync(self.windowID);
}
@end

static UIColor *launchColor(NSString *hex, UIColor *fallback) {
  if (![hex isKindOfClass:NSString.class] || hex.length != 7 || ![hex hasPrefix:@"#"]) return fallback;
  unsigned rgb = (unsigned)strtoul(hex.UTF8String + 1, NULL, 16);
  return [UIColor colorWithRed:((rgb >> 16) & 255) / 255.0 green:((rgb >> 8) & 255) / 255.0 blue:(rgb & 255) / 255.0 alpha:1];
}
static double linearChannel(double c) {
  return c <= 0.04045 ? c / 12.92 : pow((c + 0.055) / 1.055, 2.4);
}
static UIStatusBarStyle statusStyle(UIColor *color, UITraitCollection *traits) {
  CGFloat r, g, b, a, br, bg, bb, ba;
  UIColor *base = [UIColor.systemBackgroundColor resolvedColorWithTraitCollection:traits];
  if (![[color resolvedColorWithTraitCollection:traits] getRed:&r green:&g blue:&b alpha:&a] ||
      ![base getRed:&br green:&bg blue:&bb alpha:&ba]) return UIStatusBarStyleDefault;
  r = r * a + br * (1 - a); g = g * a + bg * (1 - a); b = b * a + bb * (1 - a);
  double luminance = 0.2126 * linearChannel(r) + 0.7152 * linearChannel(g) + 0.0722 * linearChannel(b);
  return luminance < 0.179 ? UIStatusBarStyleLightContent : UIStatusBarStyleDarkContent;
}
// UIKit owns interactive keyboard tracking; Go still owns all content offsets.
// This scroll view stays visually fixed and forwards its pan to the Go scroller.
@interface MyGoKeyboardScroll : UIScrollView <UIScrollViewDelegate>
@property(nonatomic, weak) MyGoSurface *surface;
@property(nonatomic) CGSize viewportSize;
@property(nonatomic) CGPoint panLast;
@property(nonatomic) CGPoint panOrigin;
@end
@implementation MyGoKeyboardScroll
- (instancetype)initWithFrame:(CGRect)frame {
 if ((self=[super initWithFrame:frame])) {
 self.delegate=self;self.keyboardDismissMode=UIScrollViewKeyboardDismissModeInteractive;
 self.alwaysBounceVertical=YES;self.delaysContentTouches=NO;
 self.showsVerticalScrollIndicator=NO;self.showsHorizontalScrollIndicator=NO;
 self.contentInsetAdjustmentBehavior=UIScrollViewContentInsetAdjustmentNever;
 self.panGestureRecognizer.minimumNumberOfTouches=1;self.panGestureRecognizer.maximumNumberOfTouches=1;
 [self.panGestureRecognizer addTarget:self action:@selector(forwardPan:)];
 }
 return self;
}
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gesture {
 if (gesture==self.panGestureRecognizer) {
 CGPoint p=[gesture locationInView:self.surface],v=[self.panGestureRecognizer velocityInView:self];
 if (p.x<24 || fabs(v.x)>=fabs(v.y) || CGRectContainsPoint(self.surface.editor.frame,p)) return NO;
 }
 return [super gestureRecognizerShouldBegin:gesture];
}
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
 self.surface.frame=(CGRect){self.contentOffset,self.viewportSize};
}
- (void)forwardPan:(UIPanGestureRecognizer *)pan {
 CGPoint translation=[pan translationInView:self];
 if (pan.state==UIGestureRecognizerStateBegan) {
 self.panLast=CGPointZero;self.panOrigin=[pan locationInView:self.surface];
 self.surface.origin=self.panOrigin;
 [self.surface commitText];self.surface.velocity=CGPointZero;
 }
 if (pan.state==UIGestureRecognizerStateBegan || pan.state==UIGestureRecognizerStateChanged) {
 goIOSScroll(self.surface.windowID,self.panOrigin.x,self.panOrigin.y,
 self.panLast.x-translation.x,self.panLast.y-translation.y);
 self.panLast=translation;
 } else if (pan.state==UIGestureRecognizerStateEnded) {
 self.surface.velocity=[pan velocityInView:self];
 [self.surface requestFrame];
 } else if (pan.state==UIGestureRecognizerStateCancelled) {
 self.surface.velocity=CGPointZero;
 }
}
@end
@interface MyGoController : UIViewController
@property(nonatomic, strong) MyGoSurface *surface;
@property(nonatomic, strong) MyGoKeyboardScroll *keyboardScroll;
@property(nonatomic, copy) NSString *keyboardDismiss;
@property(nonatomic) CGFloat keyboardTop;
@property(nonatomic, strong) UIView *launchOverlay;
@property(nonatomic) BOOL launchDismissing;
@property(nonatomic, copy) NSString *statusBarStyle;
@property(nonatomic) BOOL statusBarHidden;
- (void)dismissMyGoLaunch;
@end
@implementation MyGoController
- (BOOL)prefersStatusBarHidden { return self.statusBarHidden; }
- (UIStatusBarStyle)preferredStatusBarStyle {
 if (!self.launchOverlay && [self.statusBarStyle isEqual:@"light"]) return UIStatusBarStyleLightContent;
 if (!self.launchOverlay && [self.statusBarStyle isEqual:@"dark"]) return UIStatusBarStyleDarkContent;
  UIColor *background = self.launchOverlay ? self.launchOverlay.backgroundColor : self.view.backgroundColor;
  return statusStyle(background, self.traitCollection);
}
- (void)viewDidLoad {
  [super viewDidLoad];
  self.view.backgroundColor = UIColor.systemBackgroundColor;
 self.statusBarStyle=explicitStatusStyle;self.statusBarHidden=explicitStatusHidden;
  self.keyboardTop = CGFLOAT_MAX;
  NSDictionary *config = NSBundle.mainBundle.infoDictionary[@"MyGoLaunchScreen"];
  self.launchOverlay = [[UIView alloc] initWithFrame:self.view.bounds];
  self.launchOverlay.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  self.launchOverlay.backgroundColor = launchColor(config[@"BackgroundColor"], UIColor.systemBackgroundColor);
  self.launchOverlay.accessibilityIdentifier = @"MyGo launch screen";
  UILabel *title = [UILabel new];
  title.text = config[@"Title"] ?: NSBundle.mainBundle.infoDictionary[@"CFBundleDisplayName"];
  title.font = [UIFont boldSystemFontOfSize:32];
  title.textAlignment = NSTextAlignmentCenter;
  title.numberOfLines = 0;
  title.textColor = launchColor(config[@"ForegroundColor"], UIColor.labelColor);
  title.translatesAutoresizingMaskIntoConstraints = NO;
  [self.launchOverlay addSubview:title];
  BOOL hasImage = [config[@"Image"] boolValue];
  [NSLayoutConstraint activateConstraints:@[
    [title.centerXAnchor constraintEqualToAnchor:self.launchOverlay.centerXAnchor],
    [title.centerYAnchor constraintEqualToAnchor:self.launchOverlay.centerYAnchor constant:hasImage ? 70 : 0],
    [title.leadingAnchor constraintEqualToAnchor:self.launchOverlay.safeAreaLayoutGuide.leadingAnchor constant:20],
    [title.trailingAnchor constraintEqualToAnchor:self.launchOverlay.safeAreaLayoutGuide.trailingAnchor constant:-20]
  ]];
  if (hasImage) {
    UIImageView *logo = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"LaunchLogo.png"]];
    logo.accessibilityIdentifier = @"MyGo launch logo";
    logo.accessibilityLabel = @"MyGo logo";
    logo.isAccessibilityElement = YES;
    logo.contentMode = UIViewContentModeScaleAspectFit;
    logo.translatesAutoresizingMaskIntoConstraints = NO;
    [self.launchOverlay addSubview:logo];
    [NSLayoutConstraint activateConstraints:@[
      [logo.centerXAnchor constraintEqualToAnchor:self.launchOverlay.centerXAnchor],
      [logo.centerYAnchor constraintEqualToAnchor:self.launchOverlay.centerYAnchor constant:-30],
      [logo.widthAnchor constraintEqualToConstant:120], [logo.heightAnchor constraintEqualToConstant:120]
    ]];
  }
  [self.view addSubview:self.launchOverlay];
  [NSNotificationCenter.defaultCenter
      addObserver:self
         selector:@selector(keyboard:)
             name:UIKeyboardWillChangeFrameNotification
           object:nil];
  [NSNotificationCenter.defaultCenter addObserver:self
                                         selector:@selector(keyboard:)
                                             name:UIKeyboardWillHideNotification
                                             object:nil];
 [NSNotificationCenter.defaultCenter addObserver:self selector:@selector(keyboardHidden:) name:UIKeyboardDidHideNotification object:nil];
  for (NSNotificationName name in @[UIContentSizeCategoryDidChangeNotification,
         UIAccessibilityReduceMotionStatusDidChangeNotification,
         UIAccessibilityDarkerSystemColorsStatusDidChangeNotification]) {
    [NSNotificationCenter.defaultCenter addObserver:self selector:@selector(preferencesChanged:)
                                              name:name object:nil];
  }
}
- (void)preferencesChanged:(NSNotification *)notification { lifecycle(2); }
- (void)dismissMyGoLaunch {
  UIView *overlay = self.launchOverlay;
  if (!overlay || self.launchDismissing) return;
  self.launchDismissing = YES;
  double duration = [NSBundle.mainBundle.infoDictionary[@"MyGoLaunchScreen"][@"FadeDurationMs"] doubleValue] / 1000;
  if (UIAccessibilityIsReduceMotionEnabled()) duration = 0;
  [UIView animateWithDuration:duration animations:^{ overlay.alpha = 0; } completion:^(BOOL finished) {
    [overlay removeFromSuperview];
    self.launchOverlay = nil;
    self.launchDismissing = NO;
    [self setNeedsStatusBarAppearanceUpdate];
  }];
}
- (void)viewDidLayoutSubviews {
  [super viewDidLayoutSubviews];
  CGRect full = UIEdgeInsetsInsetRect(self.view.bounds, self.view.safeAreaInsets);
 CGRect r=full;
  r.size.height = MAX(0, MIN(CGRectGetMaxY(r), self.keyboardTop) - r.origin.y);
 // UIKit interactive dismissal requires its scroll viewport to extend
 // behind the keyboard. Only Go's content viewport is reduced.
 self.keyboardScroll.viewportSize=r.size;
 self.keyboardScroll.frame=full;
 self.keyboardScroll.contentSize=CGSizeMake(full.size.width,full.size.height+1);
 self.keyboardScroll.contentInset=UIEdgeInsetsMake(0,0,full.size.height-r.size.height,0);
 self.surface.frame=(CGRect){self.keyboardScroll.contentOffset,r.size};
}
- (void)keyboardHidden:(NSNotification *)n {
 MyGoSurface *s=self.surface;
 if (s && !s.syncing && s.editor.editable && !s.editor.isFirstResponder && [self.keyboardDismiss isEqual:@"interactive"]) goIOSDismissKeyboard(s.windowID);
}
- (void)keyboard:(NSNotification *)n {
  CGRect screen = [n.userInfo[UIKeyboardFrameEndUserInfoKey] CGRectValue];
  CGRect frame = [self.view convertRect:screen fromView:nil];
 CGRect overlap=CGRectIntersection(self.view.bounds,frame);
 // Floating/split iPad keyboards must not collapse the full-width viewport.
 BOOL docked=!CGRectIsNull(overlap) && overlap.size.width>=self.view.bounds.size.width*.9 && CGRectGetMaxY(frame)>=CGRectGetMaxY(self.view.bounds)-1;
 self.keyboardTop=![n.name isEqual:UIKeyboardWillHideNotification] && docked ? CGRectGetMinY(frame) : CGFLOAT_MAX;
  [self.view setNeedsLayout];
  [self.view layoutIfNeeded];
}
- (void)dealloc {
  [NSNotificationCenter.defaultCenter removeObserver:self];
}
@end

static BOOL interactiveKeyboardTracking(void) {
 MyGoController *c=(MyGoController *)hostWindow.rootViewController;
 MyGoKeyboardScroll *scroll=c.keyboardScroll;
 UIGestureRecognizerState state=scroll.panGestureRecognizer.state;
 return scroll.scrollEnabled && [c.keyboardDismiss isEqual:@"interactive"] &&
 (scroll.tracking || scroll.dragging || state==UIGestureRecognizerStateBegan || state==UIGestureRecognizerStateChanged);
}

@interface MyGoScene : UIResponder <UIWindowSceneDelegate>
@property(nonatomic, strong) UIWindow *window;
@end
@implementation MyGoScene
- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session
      options:(UISceneConnectionOptions *)options {
  if (![scene isKindOfClass:UIWindowScene.class]) return;
  self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene *)scene];
  hostWindow = self.window;
  self.window.overrideUserInterfaceStyle = appearance;
  self.window.rootViewController = [MyGoController new];
  [self.window makeKeyAndVisible];
  for (UIOpenURLContext *context in options.URLContexts) openURL(context.URL);
  for (NSUserActivity *activity in options.userActivities)
    if ([activity.activityType isEqual:NSUserActivityTypeBrowsingWeb]) openURL(activity.webpageURL);
  mygo_ios_notification_response((uintptr_t)(__bridge void *)options.notificationResponse);
  if (!goStarted) {
    goStarted = YES;
    dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{ MyGoIOSMain(); });
  } else {
    lifecycle(7);
  }
}
- (void)sceneWillResignActive:(UIScene *)scene {
  sceneActive = NO;
  MyGoSurface *s = hostSurface;
  [s commitText];
  [s touchesCancelled:s.contact ? [NSSet setWithObject:s.contact] : [NSSet set] withEvent:nil];
  s.displayLink.paused = YES;
  s.velocity = CGPointZero;
  s.lastTick = 0;
  lifecycle(0);
}
- (void)sceneDidBecomeActive:(UIScene *)scene {
  sceneActive = YES;
  lifecycle(1);
  [hostSurface requestFrame];
}
- (void)sceneDidEnterBackground:(UIScene *)scene {
  sceneActive = NO;
  mygo_ios_auth_cancel_all();
  hostSurface.displayLink.paused = YES;
  // Finish the synchronous checkpoint within an OS-granted background task.
  __block UIBackgroundTaskIdentifier task = UIBackgroundTaskInvalid;
  task = [UIApplication.sharedApplication beginBackgroundTaskWithName:@"MyGo checkpoint" expirationHandler:^{
    if (task != UIBackgroundTaskInvalid) {
      [UIApplication.sharedApplication endBackgroundTask:task];
      task = UIBackgroundTaskInvalid;
    }
  }];
  lifecycle(5);
  if (task != UIBackgroundTaskInvalid) [UIApplication.sharedApplication endBackgroundTask:task];
  task = UIBackgroundTaskInvalid;
}
- (void)sceneWillEnterForeground:(UIScene *)scene { lifecycle(6); }
- (void)sceneDidDisconnect:(UIScene *)scene {
  sceneActive = NO;
  [hostSurface commitText];
  mygo_ios_auth_cancel_all();
  cancelPresentations();
  hostSurface.displayLink.paused = YES;
  [hostSurface.editor resignFirstResponder];
  [hostSurface removeFromSuperview];
  hostSurface.presentationGeneration++;
  hostSurface.firstPresented = NO;
  hostSurface.presentationQueued = NO;
  lifecycle(8);
  hostWindow = nil;
  self.window = nil;
}
- (void)scene:(UIScene *)scene openURLContexts:(NSSet<UIOpenURLContext *> *)contexts {
  for (UIOpenURLContext *context in contexts) openURL(context.URL);
}
- (void)scene:(UIScene *)scene continueUserActivity:(NSUserActivity *)activity {
  if ([activity.activityType isEqual:NSUserActivityTypeBrowsingWeb]) openURL(activity.webpageURL);
}
@end

@interface MyGoDelegate : UIResponder <UIApplicationDelegate>
@end
@implementation MyGoDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)options { mygo_ios_notifications_init(); return YES; }
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)token {
 NSMutableString *hex=[NSMutableString string];const unsigned char *bytes=token.bytes;
 for (NSUInteger i=0;i<token.length;i++) [hex appendFormat:@"%02x",bytes[i]];
 goIOSPush((char *)hex.UTF8String,"");
}
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
 goIOSPush("",(char *)error.localizedDescription.UTF8String);
}
- (UISceneConfiguration *)application:(UIApplication *)app configurationForConnectingSceneSession:(UISceneSession *)session options:(UISceneConnectionOptions *)options {
  UISceneConfiguration *config = [[UISceneConfiguration alloc] initWithName:@"MyGo" sessionRole:session.role];
  config.delegateClass = MyGoScene.class;
  return config;
}
- (void)applicationDidReceiveMemoryWarning:(UIApplication *)app { lifecycle(3); }
- (void)applicationWillTerminate:(UIApplication *)app { lifecycle(4); }
@end

void mygo_ios_ready(void) {
  goReady = YES;
  lifecycle(initialLifecycle);
  NSArray<NSURL *> *urls = pendingURLs;
  NSArray<NSURL *> *files = pendingFiles;
  pendingURLs = pendingFiles = nil;
  for (NSURL *url in urls) openURL(url);
  for (NSURL *url in files) openURL(url);
  mygo_ios_notifications_ready();
}
static void firstPresented(MyGoSurface *s, NSUInteger generation) {
  if (generation != s.presentationGeneration || s.firstPresented) return;
  if (!sceneActive || !s.window) { s.presentationQueued = NO; [s requestFrame]; return; }
  s.firstPresented = YES;
  goIOSPresented(s.windowID);
  [((MyGoController *)hostWindow.rootViewController) dismissMyGoLaunch];
}
void mygo_ios_watch_drawable(uintptr_t view, uintptr_t drawable) {
#if !TARGET_OS_SIMULATOR
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  if (!s || s.firstPresented || s.presentationQueued) return;
  s.presentationQueued = YES;
  NSUInteger generation = s.presentationGeneration;
  [(__bridge id<CAMetalDrawable>)(void *)drawable addPresentedHandler:^(id<MTLDrawable> done) {
    dispatch_async(dispatch_get_main_queue(), ^{ firstPresented(s, generation); });
  }];
#endif
}
void mygo_ios_attach(uintptr_t view) {
  MyGoController *c = (MyGoController *)hostWindow.rootViewController;
  if (!c) return;
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  c.surface = s;
  c.view.backgroundColor = s.backgroundColor;
  hostWindow.backgroundColor = s.backgroundColor;
  [c setNeedsStatusBarAppearanceUpdate];
 if (!c.keyboardScroll) c.keyboardScroll=[[MyGoKeyboardScroll alloc] initWithFrame:c.view.bounds];
 c.keyboardScroll.scrollEnabled=NO;c.keyboardScroll.surface=s;
 [c.keyboardScroll addSubview:s];
 if (c.launchOverlay) [c.view insertSubview:c.keyboardScroll belowSubview:c.launchOverlay];
 else [c.view addSubview:c.keyboardScroll];
  [c.view setNeedsLayout];
  [c.view layoutIfNeeded];
  [s requestFrame];
}
int mygo_ios_start(void) {
  @autoreleasepool {
    char *argv[] = {(char *)"MyGoApp", NULL};
    return UIApplicationMain(1, argv, nil, @"MyGoDelegate");
  }
}
bool mygo_ios_is_main(void) { return NSThread.isMainThread; }
void mygo_ios_dispatch(uint64_t token) {
  dispatch_async(dispatch_get_main_queue(), ^{
    goIOSDispatch(token);
  });
}
void mygo_ios_step(void) {
  CFRunLoopRunInMode(kCFRunLoopDefaultMode, 0.01, true);
}
void mygo_ios_wake(void) { CFRunLoopWakeUp(CFRunLoopGetMain()); }
uintptr_t mygo_ios_create(uint64_t id) {
  MyGoController *c = (MyGoController *)hostWindow.rootViewController;
  if (!c)
    return 0;
  MyGoSurface *s = [[MyGoSurface alloc] initWithFrame:c.view.bounds];
  s.windowID = id;
  ((MyGoEditor *)s.editor).windowID = id;
  hostSurface = s;
  mygo_ios_attach((uintptr_t)(__bridge void *)s);
  return (uintptr_t)(__bridge void *)s;
}
void mygo_ios_close(uintptr_t view) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  [s.displayLink invalidate];
  [s.editor resignFirstResponder];
  [s removeFromSuperview];
  ((MyGoController *)hostWindow.rootViewController).surface = nil;
  if (hostSurface == s) hostSurface = nil;
}
void mygo_ios_show(uintptr_t view, bool visible) {
  ((__bridge MyGoSurface *)(void *)view).hidden = !visible;
}
void mygo_ios_background(uintptr_t view, double r, double g, double b, double a) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  if (!s) return;
  UIColor *color = [UIColor colorWithRed:r green:g blue:b alpha:a];
  s.backgroundColor = color;
  MyGoController *c = (MyGoController *)hostWindow.rootViewController;
  if (c.surface == s) {
    c.view.backgroundColor = color;
    hostWindow.backgroundColor = color;
    [c setNeedsStatusBarAppearanceUpdate];
  }
}
uintptr_t mygo_ios_layer(uintptr_t view) {
#if TARGET_OS_SIMULATOR
  // The simulator SDK omits drawable presentation callbacks. Use the
  // existing CPU presenter and its Core Animation first-frame completion.
  return 0;
#else
  return (uintptr_t)(__bridge void *)((__bridge MyGoSurface *)(void *)view)
      .layer;
#endif
}
void mygo_ios_size(uintptr_t view, double *w, double *h, double *scale) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  *w = s.bounds.size.width;
  *h = s.bounds.size.height;
  *scale = s.window.windowScene.screen.scale ?: s.traitCollection.displayScale;
}
double mygo_ios_hz(uintptr_t view) {
  return ((__bridge MyGoSurface *)(void *)view)
      .window.screen.maximumFramesPerSecond;
}
void mygo_ios_frame(uintptr_t view) {
  [((__bridge MyGoSurface *)(void *)view) requestFrame];
}
void mygo_ios_pixels(uintptr_t view, const void *pixels, int stride, int w,
                     int h) {
  NSData *data = [NSData dataWithBytes:pixels length:stride * h];
  CGDataProviderRef p =
      CGDataProviderCreateWithCFData((__bridge CFDataRef)data);
  CGColorSpaceRef space = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);
  CGImageRef image = CGImageCreate(w, h, 8, 32, stride, space,
                                   kCGBitmapByteOrder32Little |
                                       kCGImageAlphaPremultipliedFirst,
                                   p, NULL, false, kCGRenderingIntentDefault);
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  [CATransaction begin];
  [CATransaction setDisableActions:YES];
  NSUInteger generation = s.presentationGeneration;
  if (!s.firstPresented) [CATransaction setCompletionBlock:^{ firstPresented(s, generation); }];
  s.layer.contents = (__bridge id)image;
  [CATransaction commit];
  CGImageRelease(image);
  CGColorSpaceRelease(space);
  CGDataProviderRelease(p);
}
void mygo_ios_input_history(uintptr_t view, bool undo, bool redo) {
  MyGoEditor *editor = (MyGoEditor *)((__bridge MyGoSurface *)(void *)view).editor;
  editor.goCanUndo = undo;
  editor.goCanRedo = redo;
}
void mygo_ios_input_accessory(uintptr_t view, uint64_t owner, const char *json) {
 MyGoEditor *editor=(MyGoEditor *)((__bridge MyGoSurface *)(void *)view).editor;
 NSString *value=str(json);
 MyGoInputAccessory *accessory=[editor.inputAccessoryView isKindOfClass:MyGoInputAccessory.class] ? (MyGoInputAccessory *)editor.inputAccessoryView : nil;
 if ([editor.accessoryJSON isEqual:value]) {
  accessory.ownerID=owner;
  return;
 }
 editor.accessoryJSON=value;
 BOOL installed=accessory!=nil;
 NSArray *actions=value.length ? [NSJSONSerialization JSONObjectWithData:[value dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil] : nil;
 if (actions.count) {
  if (!accessory) accessory=[MyGoInputAccessory new];
  accessory.editor=editor;accessory.windowID=editor.windowID;accessory.ownerID=owner;
  accessory.actions=actions;accessory.expanded=NO;
  [accessory rebuild];
  editor.inputAccessoryView=accessory;
 } else editor.inputAccessoryView=nil;
 if (editor.isFirstResponder && installed!=(actions.count>0)) [editor reloadInputViews];
}
void mygo_ios_input(uintptr_t view, bool active, bool readonly, bool password, bool multiline,
                    const char *text, int start, int end, double x, double y,
                    double w, double h) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  UITextView *e = s.editor;
  BOOL syncing = s.syncing;
  s.syncing = YES;
 MyGoController *controller=(MyGoController *)hostWindow.rootViewController;
 controller.keyboardScroll.scrollEnabled=active && !readonly && [controller.keyboardDismiss isEqual:@"interactive"];
  if (!active) {
    [UIMenuController.sharedMenuController hideMenuFromView:e];
    e.tintColor = UIColor.clearColor;
    ((MyGoEditor *)e).fieldID = 0;
    e.frame = CGRectZero;
    [e resignFirstResponder];
    if (sceneActive && s.window) [s becomeFirstResponder];
    if (@available(iOS 17.0, *)) ((MyGoEditor *)e).selectionDisplay.activated = NO;
    s.syncing = syncing;
    return;
  }
  BOOL changedReadOnly = e.editable==readonly;
 e.editable = !readonly;
 if (readonly && !e.inputView) e.inputView=[UIView new];
 if (!readonly && e.inputView) e.inputView=nil;
  BOOL changedPassword = e.secureTextEntry != password;
  e.secureTextEntry = password;
  ((MyGoEditor *)e).multiline = multiline;
  ((MyGoEditor *)e).goCaret = CGRectMake(x, y, w, h);
  e.tintColor = ((MyGoEditor *)e).fieldID && !password && !e.markedTextRange && mygo_ios_native_selection()
      ? UIColor.systemBlueColor : UIColor.clearColor;
  if (!s.sending && !e.markedTextRange) {
    NSString *t = str(text);
    if (![e.text isEqual:t])
      e.text = t;
    s.synchronizedText = t;
    NSUInteger a = units(t, start), z = units(t, end);
    e.selectedRange = NSMakeRange(a, z - a);
    s.contextLength = runes(t);
  }
  s.contextLength = runes(str(text));
  // Go fields share one UITextView. Apply security and input-view changes
  // after all traits/text are set, so Tab into a password cannot keep the
  // previous field's composing keyboard session.
  if ((changedReadOnly || changedPassword) && e.isFirstResponder) [e reloadInputViews];
  if (!e.isFirstResponder && !interactiveKeyboardTracking())
    [e becomeFirstResponder];
  if (@available(iOS 17.0, *)) {
    UITextSelectionDisplayInteraction *selection = ((MyGoEditor *)e).selectionDisplay;
    selection.activated = ((MyGoEditor *)e).fieldID && !password && !e.markedTextRange;
    [selection setNeedsSelectionUpdate];
    [selection layoutManagedSubviews];
    // These views were created while the keyboard proxy's tint was clear.
    // UITextView updates its own internal display, so update our display too.
    selection.cursorView.tintColor = e.tintColor;
    selection.cursorView.blinking = YES;
    selection.highlightView.tintColor = e.tintColor;
    selection.highlightView.alpha = 0.2;
    for (UIView *handle in selection.handleViews) handle.tintColor = e.tintColor;
  }
  s.syncing = syncing;
}
void mygo_ios_input_bounds(uintptr_t view, const char *id, double x, double y, double w, double h) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  MyGoEditor *e = (MyGoEditor *)s.editor;
  BOOL syncing = s.syncing;
  s.syncing = YES;
  uint64_t field = strtoull(id, NULL, 10);
  if (e.fieldID != field) [UIMenuController.sharedMenuController hideMenuFromView:e];
  e.fieldID = field;
  e.frame = CGRectMake(x, y, MAX(0, w), MAX(0, h));
  s.syncing = syncing;
}
bool mygo_ios_native_selection(void) {
  if (@available(iOS 17.0, *)) return true;
  return false;
}
void mygo_ios_input_options(uintptr_t view, const char *json) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  UITextView *e = s.editor;
  NSDictionary *options = [NSJSONSerialization JSONObjectWithData:[str(json) dataUsingEncoding:NSUTF8StringEncoding]
                                                        options:0 error:nil];
 MyGoController *controller=(MyGoController *)hostWindow.rootViewController;
 controller.keyboardDismiss=options[@"Dismiss"] ?: @"";
  NSDictionary *keyboards = @{@"text": @(UIKeyboardTypeDefault), @"ascii": @(UIKeyboardTypeASCIICapable),
    @"number": @(UIKeyboardTypeNumberPad), @"decimal": @(UIKeyboardTypeDecimalPad),
    @"phone": @(UIKeyboardTypePhonePad), @"email": @(UIKeyboardTypeEmailAddress), @"url": @(UIKeyboardTypeURL)};
  NSDictionary *returns = @{@"done": @(UIReturnKeyDone), @"go": @(UIReturnKeyGo), @"next": @(UIReturnKeyNext),
    @"search": @(UIReturnKeySearch), @"send": @(UIReturnKeySend), @"continue": @(UIReturnKeyContinue)};
  NSDictionary *contents = @{@"username": UITextContentTypeUsername, @"password": UITextContentTypePassword,
    @"newPassword": UITextContentTypeNewPassword, @"oneTimeCode": UITextContentTypeOneTimeCode,
    @"emailAddress": UITextContentTypeEmailAddress, @"telephoneNumber": UITextContentTypeTelephoneNumber,
    @"name": UITextContentTypeName, @"fullStreetAddress": UITextContentTypeFullStreetAddress,
    @"postalCode": UITextContentTypePostalCode};
  UIKeyboardType keyboard = [keyboards[options[@"Keyboard"]] integerValue];
  UIReturnKeyType returnKey = [returns[options[@"Return"]] integerValue];
  NSString *content = contents[options[@"Content"]] ?: @"";
  NSString *correction = options[@"Correction"];
  UITextAutocorrectionType correct = [correction isEqual:@"off"] ? UITextAutocorrectionTypeNo :
    [correction isEqual:@"on"] ? UITextAutocorrectionTypeYes : UITextAutocorrectionTypeDefault;
  NSString *capitalization = options[@"Capitalization"];
  UITextAutocapitalizationType capitals = [capitalization isEqual:@"none"] ? UITextAutocapitalizationTypeNone :
    [capitalization isEqual:@"words"] ? UITextAutocapitalizationTypeWords :
    [capitalization isEqual:@"all"] ? UITextAutocapitalizationTypeAllCharacters : UITextAutocapitalizationTypeSentences;
  BOOL changed = e.keyboardType != keyboard || e.returnKeyType != returnKey ||
    ![e.textContentType isEqual:content] || e.autocorrectionType != correct || e.autocapitalizationType != capitals;
  e.keyboardType = keyboard;
  e.returnKeyType = returnKey;
  e.textContentType = content;
  e.autocorrectionType = correct;
  e.autocapitalizationType = capitals;
  if (changed && e.isFirstResponder) [e reloadInputViews];
}
void mygo_ios_preferences(bool *motion, bool *contrast, double *scale) {
  *motion = UIAccessibilityIsReduceMotionEnabled();
  *contrast = UIAccessibilityDarkerSystemColorsEnabled();
  *scale = [[UIFontMetrics metricsForTextStyle:UIFontTextStyleBody] scaledValueForValue:17
                                                      compatibleWithTraitCollection:hostWindow.traitCollection] / 17;
}
void mygo_ios_access(uintptr_t view, const char *json) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  NSDictionary *t = [NSJSONSerialization
      JSONObjectWithData:[str(json) dataUsingEncoding:NSUTF8StringEncoding]
                 options:0
                   error:nil];
  NSMutableArray *a = [NSMutableArray array];
  s.editor.isAccessibilityElement = NO;
  for (NSDictionary *n in t[@"Nodes"]) {
    unsigned states = [n[@"States"] unsignedIntValue];
    int role = [n[@"Role"] intValue];
    if (states & (1 << 10))
      continue;
    NSString *label = n[@"Label"] ?: @"";
    NSString *value = n[@"Value"] ?: @"";
    if (role == 0 || (!label.length && !value.length))
      continue;
    MyGoAccess *e = [[MyGoAccess alloc] initWithAccessibilityContainer:s];
    e.windowID = s.windowID;
    e.nodeID = strtoull([n[@"ID"] UTF8String], NULL, 10);
    e.actions = [n[@"Actions"] unsignedIntValue];
    e.isAccessibilityElement = YES;
    e.accessibilityLabel = label;
    e.accessibilityValue = value;
    e.accessibilityHint = n[@"Description"];
    e.accessibilityIdentifier = label.length ? label : value;
    UIAccessibilityTraits traits = UIAccessibilityTraitNone;
    if ((e.actions & 1) && role != 3)
      traits |= UIAccessibilityTraitButton;
    if (role == 3)
      traits |= UIAccessibilityTraitLink;
    if (role == 1)
      traits |= UIAccessibilityTraitStaticText;
    if (role == 10)
      traits |= UIAccessibilityTraitImage;
    if (role == 7 || role == 35)
      traits |= UIAccessibilityTraitAdjustable;
    if (role == 43)
      traits |= UIAccessibilityTraitHeader;
    if (states & (1 << 1))
      traits |= UIAccessibilityTraitNotEnabled;
    if (states & ((1 << 2) | (1 << 4)))
      traits |= UIAccessibilityTraitSelected;
    e.accessibilityTraits = traits;
    NSDictionary *b = n[@"Bounds"];
    CGRect bounds =
        CGRectMake([b[@"X"] doubleValue], [b[@"Y"] doubleValue],
                   [b[@"W"] doubleValue], [b[@"H"] doubleValue]);
    bounds = CGRectIntersection(bounds, s.bounds);
    if (CGRectIsEmpty(bounds)) continue;
    e.accessibilityFrameInContainerSpace = bounds;
    // Expose the actual first responder for the focused field. UIKit then
    // provides editable-text and keyboard-focus semantics to VoiceOver
    // and UI automation while Go continues drawing and owning its value.
    if ([n[@"ID"] isEqual:t[@"Focus"]] &&
        (role == 9 || role == 32 || (role == 1 && ((MyGoEditor *)s.editor).fieldID == e.nodeID))) {
      s.editor.isAccessibilityElement = YES;
      s.editor.accessibilityLabel = label;
      s.editor.accessibilityIdentifier = label;
      s.editor.accessibilityHint = n[@"Description"];
      ((MyGoEditor *)s.editor).goAccessibilityFrame =
          [s convertRect:bounds toView:nil];
      [a addObject:s.editor];
      continue;
    }
    [a addObject:e];
  }
  s.goAccessibilityElements = a;
  NSArray *announcements = t[@"Announcements"];
  if ([announcements isKindOfClass:NSArray.class]) {
    for (NSString *announcement in announcements)
      UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification,
                                      announcement);
  }
}
bool mygo_ios_dark(void) {
  return hostWindow.traitCollection.userInterfaceStyle ==
         UIUserInterfaceStyleDark;
}
void mygo_ios_theme(int mode) {
  appearance = mode;
  hostWindow.overrideUserInterfaceStyle = appearance;
}
char *mygo_ios_clipboard(void) {
  return strdup((UIPasteboard.generalPasteboard.string ?: @"").UTF8String);
}
void mygo_ios_set_clipboard(const char *text) {
  UIPasteboard.generalPasteboard.string = str(text);
}
char *mygo_ios_locale(void) {
  return strdup(NSLocale.currentLocale.localeIdentifier.UTF8String);
}
char *mygo_ios_home(void) { return strdup(NSHomeDirectory().UTF8String); }
bool mygo_ios_open(const char *url) {
  NSURL *u = [NSURL URLWithString:str(url)];
  if (!u || ![UIApplication.sharedApplication canOpenURL:u])
    return false;
  [UIApplication.sharedApplication openURL:u options:@{} completionHandler:nil];
  return true;
}
void mygo_ios_memory(uintptr_t view) {
  MyGoSurface *s = (__bridge MyGoSurface *)(void *)view;
  s.layer.contents = nil;
  [s requestFrame];
}

// Keep presentation delegates alive even though UIKit's delegate properties
// are weak. The token also makes dismissal/completion races idempotent.
@interface MyGoPresentation : NSObject <UIAdaptivePresentationControllerDelegate, UIPopoverPresentationControllerDelegate>
@property(nonatomic) uint64_t token;
@property(nonatomic) NSInteger cancelIndex;
@property(nonatomic, copy) NSDictionary *cancellationResult;
- (BOOL)pending;
- (void)cancel;
@property(nonatomic, strong) UIViewController *controller;
- (void)finish:(NSDictionary *)result error:(NSError *)error;
@end
static NSMutableDictionary<NSNumber *, MyGoPresentation *> *presentations;
@implementation MyGoPresentation
- (BOOL)pending { return presentations[@(self.token)] == self; }
- (void)cancel {
  [self finish:self.cancellationResult ?: @{@"Response": @(self.cancelIndex), @"CheckboxChecked": @NO} error:nil];
}
- (void)finish:(NSDictionary *)result error:(NSError *)error {
  if (!NSThread.isMainThread) {
    dispatch_async(dispatch_get_main_queue(), ^{ [self finish:result error:error]; });
    return;
  }
  if (!presentations[@(self.token)]) return;
  [presentations removeObjectForKey:@(self.token)];
  self.controller = nil;
  NSData *data = [NSJSONSerialization dataWithJSONObject:result ?: @{} options:0 error:nil];
  NSString *json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
  goIOSSystemResult(self.token, (char *)json.UTF8String, error ? 2 : 0, (char *)error.localizedDescription.UTF8String);
}
- (void)presentationControllerDidDismiss:(UIPresentationController *)presentationController {
  [self cancel];
}
- (void)popoverPresentationControllerDidDismissPopover:(UIPopoverPresentationController *)popover {
  [self presentationControllerDidDismiss:popover];
}
@end
static UIViewController *systemPresenter(uint64_t token) {
  UIViewController *root = hostWindow.rootViewController;
  if (!root || !root.view.window || hostWindow.windowScene.activationState != UISceneActivationStateForegroundActive) {
    goIOSSystemResult(token, NULL, 2, "mygo: system presentation requires an active Scene");
    return nil;
  }
  if (root.presentedViewController || presentations.count || mygo_ios_auth_pending()) {
    goIOSSystemResult(token, NULL, 2, "mygo: another system presentation is active");
    return nil;
  }
  return root;
}
int mygo_ios_auth_state(void) {
  UIViewController *root = hostWindow.rootViewController;
  if (!root || !root.view.window || !sceneActive) return 1;
  return root.presentedViewController || presentations.count ? 2 : 0;
}
static void cancelPresentations(void) {
  NSArray<MyGoPresentation *> *active = presentations.allValues;
  for (MyGoPresentation *delegate in active) {
    [delegate.controller dismissViewControllerAnimated:NO completion:nil];
    [delegate cancel];
  }
}
static MyGoPresentation *registerPresentation(MyGoPresentation *delegate, uint64_t token, UIViewController *controller, UIViewController *parent) {
  if (!presentations) presentations = [NSMutableDictionary dictionary];
  delegate.token = token;
  delegate.controller = controller;
  presentations[@(token)] = delegate;
  // Asking an action sheet for its popover controller can opt into popover
  // presentation even on a phone, hiding the cancel action. Anchor only iPad.
  UIPopoverPresentationController *popover = parent.traitCollection.userInterfaceIdiom == UIUserInterfaceIdiomPad ? controller.popoverPresentationController : nil;
  if (popover) {
    popover.sourceView = parent.view;
    popover.sourceRect = CGRectMake(CGRectGetMidX(parent.view.bounds), CGRectGetMidY(parent.view.bounds), 1, 1);
    popover.permittedArrowDirections = 0;
    if (![controller isKindOfClass:UIAlertController.class]) popover.delegate = delegate;
  }
  // UIAlertController owns its presentation delegate and asserts if an app
  // replaces it. Its cancel action handles outside-popover dismissal.
  if (![controller isKindOfClass:UIAlertController.class]) controller.presentationController.delegate = delegate;
  return delegate;
}
static MyGoPresentation *trackPresentation(uint64_t token, UIViewController *controller, UIViewController *parent) {
  return registerPresentation([MyGoPresentation new], token, controller, parent);
}
void mygo_ios_message(uint64_t token, const char *json) {
  NSDictionary *o = [NSJSONSerialization JSONObjectWithData:[str(json) dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];
  if ([o[@"CheckboxLabel"] length]) {
    goIOSSystemResult(token, NULL, 1, NULL);
    return;
  }
  UIViewController *parent = systemPresenter(token);
  if (!parent) return;
  NSString *message = o[@"Message"];
  if ([o[@"Detail"] length]) message = [message stringByAppendingFormat:@"\n\n%@", o[@"Detail"]];
  UIAlertControllerStyle style = [o[@"Style"] isEqual:@"actionSheet"] ? UIAlertControllerStyleActionSheet : UIAlertControllerStyleAlert;
  UIAlertController *alert = [UIAlertController alertControllerWithTitle:o[@"Title"] message:message preferredStyle:style];
  MyGoPresentation *delegate = trackPresentation(token, alert, parent);
  delegate.cancelIndex = [o[@"CancelID"] integerValue];
  NSArray *buttons = o[@"Buttons"], *destructive = o[@"DestructiveButtons"];
  BOOL hasCancel = NO;
  for (NSUInteger i = 0; i < buttons.count; i++) {
    UIAlertActionStyle actionStyle = i == delegate.cancelIndex && (buttons.count > 1 || style == UIAlertControllerStyleActionSheet) ? UIAlertActionStyleCancel : UIAlertActionStyleDefault;
    if ([destructive isKindOfClass:NSArray.class] && [destructive containsObject:@(i)]) actionStyle = UIAlertActionStyleDestructive;
    if (actionStyle == UIAlertActionStyleCancel) hasCancel = YES;
    UIAlertAction *action = [UIAlertAction actionWithTitle:buttons[i] style:actionStyle handler:^(UIAlertAction *selected) {
      [delegate finish:@{@"Response": @(i), @"CheckboxChecked": @NO} error:nil];
    }];
    [alert addAction:action];
    if (style == UIAlertControllerStyleAlert && i == [o[@"DefaultID"] integerValue]) alert.preferredAction = action;
  }
  if (style == UIAlertControllerStyleActionSheet && !hasCancel) {
    [alert addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:^(UIAlertAction *action) {
      [delegate finish:@{@"Response": @(delegate.cancelIndex), @"CheckboxChecked": @NO} error:nil];
    }]];
  }
  [parent presentViewController:alert animated:YES completion:nil];
}
void mygo_ios_share(uint64_t token, const char *json) {
  NSDictionary *o = [NSJSONSerialization JSONObjectWithData:[str(json) dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];
  UIViewController *parent = systemPresenter(token);
  if (!parent) return;
  NSMutableArray *items = [NSMutableArray array];
  if ([o[@"Text"] length]) [items addObject:o[@"Text"]];
  if ([o[@"URL"] length]) [items addObject:[NSURL URLWithString:o[@"URL"]]];
  NSArray *files = o[@"Files"];
  if ([files isKindOfClass:NSArray.class]) for (NSString *path in files) {
    if (![NSFileManager.defaultManager fileExistsAtPath:path]) {
      goIOSSystemResult(token, NULL, 2, "mygo: shared file no longer exists");
      return;
    }
    [items addObject:[NSURL fileURLWithPath:path]];
  }
  UIActivityViewController *activity = [[UIActivityViewController alloc] initWithActivityItems:items applicationActivities:nil];
  MyGoPresentation *delegate = trackPresentation(token, activity, parent);
  delegate.cancellationResult = @{@"Completed": @NO, @"Activity": @""};
  activity.completionWithItemsHandler = ^(UIActivityType type, BOOL completed, NSArray *returned, NSError *error) {
    [delegate finish:@{@"Completed": @(completed), @"Activity": type ?: @""} error:error];
  };
  [parent presentViewController:activity animated:YES completion:nil];
  activity.presentationController.delegate = delegate;
}

// Provider URLs and NSItemProvider representations are temporary. Copy them
// before completing the native delegate, and never hand security-scoped URLs
// to Go. Disk work stays off UIKit's main thread.
static NSError *fileError(NSString *message) {
  return [NSError errorWithDomain:@"MyGoFiles" code:1 userInfo:@{NSLocalizedDescriptionKey:message}];
}
static NSString *copyImport(NSURL *source, NSString *name, NSError **error) {
  NSFileManager *fm = NSFileManager.defaultManager;
  NSURL *cache = [[fm URLsForDirectory:NSCachesDirectory inDomains:NSUserDomainMask].firstObject URLByAppendingPathComponent:@"MyGoImports" isDirectory:YES];
  if (![fm createDirectoryAtURL:cache withIntermediateDirectories:YES attributes:nil error:error]) return nil;
  NSNumber *regular;
  if (![source getResourceValue:&regular forKey:NSURLIsRegularFileKey error:error]) return nil;
  if (!regular.boolValue) { *error = fileError(@"mygo: importing requires a regular file"); return nil; }
  NSString *filename = name.lastPathComponent;
  if (!filename.length || [filename isEqual:@"."] || [filename isEqual:@".."]) filename = @"file";
  NSURL *target = [cache URLByAppendingPathComponent:[NSString stringWithFormat:@"%@-%@", NSUUID.UUID.UUIDString, filename]];
  if (![fm copyItemAtURL:source toURL:target error:error]) {
    [fm removeItemAtURL:target error:nil];
    return nil;
  }
  return target.path;
}
static void removeImports(NSArray<NSString *> *paths) {
  for (NSString *path in paths) [NSFileManager.defaultManager removeItemAtPath:path error:nil];
}

@interface MyGoFilePresentation : MyGoPresentation <UIDocumentPickerDelegate, PHPickerViewControllerDelegate>
@property(nonatomic) BOOL exporting;
@property(nonatomic) BOOL loading;
@end
@implementation MyGoFilePresentation
- (void)completeImports:(NSArray<NSString *> *)paths error:(NSError *)error {
  NSAssert(NSThread.isMainThread, @"Import results must return on the main thread");
  if (![self pending] || error) {
    dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY, 0), ^{ removeImports(paths); });
    if ([self pending]) [self finish:nil error:error];
    return;
  }
  [self finish:@{@"Paths":paths} error:nil];
}
- (void)documentPickerWasCancelled:(UIDocumentPickerViewController *)controller {
  [self cancel];
}
- (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls {
  if (![self pending] || self.loading) return;
  self.loading = YES;
  if (self.exporting) {
    [self finish:@{@"Completed":@((BOOL)(urls.count > 0))} error:nil];
    return;
  }
  // Keep scope valid while coordinating and copying on a worker queue.
  NSMutableArray<NSURL *> *scopes = [NSMutableArray array];
  for (NSURL *url in urls) if ([url startAccessingSecurityScopedResource]) [scopes addObject:url];
  dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY, 0), ^{
    @autoreleasepool {
      NSMutableArray<NSString *> *paths = [NSMutableArray array];
      __block NSError *error;
      for (NSURL *url in urls) {
        NSError *coordinationError;
        NSFileCoordinator *coordinator = [[NSFileCoordinator alloc] initWithFilePresenter:nil];
        [coordinator coordinateReadingItemAtURL:url options:NSFileCoordinatorReadingWithoutChanges error:&coordinationError byAccessor:^(NSURL *readURL) {
          NSString *path = copyImport(readURL, url.lastPathComponent, &error);
          if (path) [paths addObject:path];
        }];
        if (!error) error = coordinationError;
        if (error) break;
      }
      for (NSURL *url in scopes) [url stopAccessingSecurityScopedResource];
      dispatch_async(dispatch_get_main_queue(), ^{ [self completeImports:paths error:error]; });
    }
  });
}
- (void)picker:(PHPickerViewController *)picker didFinishPicking:(NSArray<PHPickerResult *> *)results {
  if (![self pending] || self.loading) return;
  self.loading = YES;
  [picker dismissViewControllerAnimated:YES completion:nil];
  if (!results.count) { [self cancel]; return; }
  dispatch_group_t group = dispatch_group_create();
  NSLock *lock = [NSLock new];
  NSMutableArray *paths = [NSMutableArray array];
  for (NSUInteger i = 0; i < results.count; i++) [paths addObject:NSNull.null];
  __block NSError *batchError;
  [results enumerateObjectsUsingBlock:^(PHPickerResult *result, NSUInteger index, BOOL *stop) {
    NSItemProvider *provider = result.itemProvider;
    NSString *type;
    for (NSString *identifier in provider.registeredTypeIdentifiers) {
      if ([[UTType typeWithIdentifier:identifier] conformsToType:UTTypeImage]) { type = identifier; break; }
    }
    if (!type) { [lock lock]; if (!batchError) batchError = fileError(@"mygo: selected photo has no file representation"); [lock unlock]; return; }
    dispatch_group_enter(group);
    [provider loadFileRepresentationForTypeIdentifier:type completionHandler:^(NSURL *url, NSError *error) {
      @autoreleasepool {
        NSString *path;
        if (url && !error) {
          NSString *name = provider.suggestedName.lastPathComponent;
          if (!name.length) name = url.lastPathComponent;
          NSString *ext = url.pathExtension.length ? url.pathExtension : [UTType typeWithIdentifier:type].preferredFilenameExtension;
          if (ext.length && ![name.pathExtension.lowercaseString isEqual:ext.lowercaseString])
            name = [name.stringByDeletingPathExtension stringByAppendingPathExtension:ext];
          // The system deletes url after this completion handler returns.
          path = copyImport(url, name, &error);
        }
        if (!path && !error) error = fileError(@"mygo: photo provider returned no file");
        [lock lock];
        if (path) paths[index] = path;
        if (error && !batchError) batchError = error;
        [lock unlock];
        dispatch_group_leave(group);
      }
    }];
  }];
  dispatch_group_notify(group, dispatch_get_main_queue(), ^{
    NSMutableArray *copied = [NSMutableArray array];
    for (id path in paths) if ([path isKindOfClass:NSString.class]) [copied addObject:path];
    [self completeImports:copied error:batchError];
  });
}
@end

static void presentFiles(uint64_t token, UIDocumentPickerViewController *picker, UIViewController *parent, BOOL exporting) {
  MyGoFilePresentation *delegate = [MyGoFilePresentation new];
  delegate.exporting = exporting;
  delegate.cancellationResult = exporting ? @{@"Completed":@NO} : @{@"Paths":@[]};
  picker.modalPresentationStyle = UIModalPresentationPageSheet;
  registerPresentation(delegate, token, picker, parent);
  picker.delegate = delegate;
  [parent presentViewController:picker animated:YES completion:nil];
  picker.presentationController.delegate = delegate;
}
void mygo_ios_open_files(uint64_t token, const char *json) {
  NSDictionary *o = [NSJSONSerialization JSONObjectWithData:[str(json) dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];
  if ([o[@"OpenDirectories"] boolValue]) { goIOSSystemResult(token, NULL, 1, NULL); return; }
  UIViewController *parent = systemPresenter(token);
  if (!parent) return;
  NSMutableArray<UTType *> *types = [NSMutableArray array];
  NSArray *filters = o[@"Filters"];
  BOOL anyType = NO;
  if ([filters isKindOfClass:NSArray.class]) for (NSDictionary *filter in filters) {
    NSArray *extensions = filter[@"Extensions"];
    if (![extensions isKindOfClass:NSArray.class]) continue;
    for (NSString *extension in extensions) {
      if ([extension isEqual:@"*"]) { anyType = YES; break; }
      UTType *type = [UTType typeWithFilenameExtension:extension];
      if (!type) { goIOSSystemResult(token, NULL, 2, "mygo: file filter extension has no iOS content type"); return; }
      if (![types containsObject:type]) [types addObject:type];
    }
    if (anyType) break;
  }
  if (anyType) { [types removeAllObjects]; [types addObject:UTTypeItem]; }
  if (!types.count) [types addObject:UTTypeItem];
  // Borrow scoped access only while making our cache copy. Asking UIKit to
  // import too would leave an additional caller-owned Inbox copy behind.
  UIDocumentPickerViewController *picker = [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:types asCopy:NO];
  picker.allowsMultipleSelection = [o[@"Multiple"] boolValue];
  if ([o[@"Title"] length]) picker.title = o[@"Title"];
  presentFiles(token, picker, parent, NO);
}
void mygo_ios_export_files(uint64_t token, const char *json) {
  NSDictionary *o = [NSJSONSerialization JSONObjectWithData:[str(json) dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];
  UIViewController *parent = systemPresenter(token);
  if (!parent) return;
  NSMutableArray<NSURL *> *urls = [NSMutableArray array];
  for (NSString *path in o[@"Files"]) {
    BOOL directory;
    if (![NSFileManager.defaultManager fileExistsAtPath:path isDirectory:&directory] || directory) {
      goIOSSystemResult(token, NULL, 2, "mygo: exported file no longer exists"); return;
    }
    [urls addObject:[NSURL fileURLWithPath:path]];
  }
  UIDocumentPickerViewController *picker = [[UIDocumentPickerViewController alloc] initForExportingURLs:urls asCopy:YES];
  if ([o[@"Title"] length]) picker.title = o[@"Title"];
  presentFiles(token, picker, parent, YES);
}
void mygo_ios_photos(uint64_t token, const char *json) {
  NSDictionary *o = [NSJSONSerialization JSONObjectWithData:[str(json) dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];
  UIViewController *parent = systemPresenter(token);
  if (!parent) return;
  PHPickerConfiguration *config = [PHPickerConfiguration new];
  config.filter = PHPickerFilter.imagesFilter;
  config.selectionLimit = [o[@"Multiple"] boolValue] ? 0 : 1;
  config.preferredAssetRepresentationMode = PHPickerConfigurationAssetRepresentationModeCurrent;
  PHPickerViewController *picker = [[PHPickerViewController alloc] initWithConfiguration:config];
  MyGoFilePresentation *delegate = [MyGoFilePresentation new];
  delegate.cancellationResult = @{@"Paths":@[]};
  registerPresentation(delegate, token, picker, parent);
  picker.delegate = delegate;
  [parent presentViewController:picker animated:YES completion:nil];
  picker.presentationController.delegate = delegate;
}

void mygo_ios_status_bar(const char *style, bool hidden) {
 MyGoController *c=(MyGoController *)hostWindow.rootViewController;
 explicitStatusStyle=str(style);explicitStatusHidden=hidden;
 c.statusBarStyle=explicitStatusStyle;c.statusBarHidden=hidden;
 [c setNeedsStatusBarAppearanceUpdate];
}
